// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package pgq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO auth_accounts (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, role, banned, created_at
`

type CreateAccountParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	Banned    bool               `json:"banned"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.PasswordHash, arg.Role)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (account_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token, expires_at
`

type CreateSessionParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.AccountID, arg.Token, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.Token, &i.ExpiresAt)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM auth_accounts WHERE username = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteAccount, username)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM auth_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, password_hash, role, banned, created_at, updated_at
FROM auth_accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (AuthAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i AuthAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, password_hash, role, banned, created_at, updated_at
FROM auth_accounts WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (AuthAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i AuthAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.account_id, s.token, s.expires_at, a.username, a.role, a.banned
FROM auth_sessions s
JOIN auth_accounts a ON a.id = s.account_id
WHERE s.token = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	Banned    bool               `json:"banned"`
}

func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Token,
		&i.ExpiresAt,
		&i.Username,
		&i.Role,
		&i.Banned,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, role, banned, created_at FROM auth_accounts ORDER BY username
`

type ListAccountsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	Banned    bool               `json:"banned"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBanned = `-- name: SetBanned :exec
UPDATE auth_accounts SET banned = $1, updated_at = now() WHERE username = $2
`

type SetBannedParams struct {
	Banned   bool   `json:"banned"`
	Username string `json:"username"`
}

func (q *Queries) SetBanned(ctx context.Context, arg SetBannedParams) error {
	_, err := q.db.Exec(ctx, setBanned, arg.Banned, arg.Username)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE auth_sessions SET expires_at = $1 WHERE token = $2
`

type TouchSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Token     string             `json:"token"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.Token)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE auth_accounts SET password_hash = $1, updated_at = now() WHERE username = $2
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.Username)
	return err
}
