// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAccount struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Banned       bool               `json:"banned"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SharedArenaSession struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	WorldID   string             `json:"world_id"`
	GameType  string             `json:"game_type"`
	Wave      int32              `json:"wave"`
	Enemies   string             `json:"enemies"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

type SharedBounty struct {
	WorldID   string `json:"world_id"`
	RoomID    string `json:"room_id"`
	NpcID     string `json:"npc_id"`
	CreatedAt int32  `json:"created_at"`
}

type SharedBuild struct {
	WorldID  string             `json:"world_id"`
	RoomID   string             `json:"room_id"`
	BuildID  string             `json:"build_id"`
	PlacedBy pgtype.UUID        `json:"placed_by"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

type SharedChest struct {
	ID       pgtype.UUID `json:"id"`
	WorldID  string      `json:"world_id"`
	RoomID   string      `json:"room_id"`
	ItemID   string      `json:"item_id"`
	ItemName string      `json:"item_name"`
	StoredBy pgtype.UUID `json:"stored_by"`
}

type SharedCrop struct {
	WorldID         string `json:"world_id"`
	RoomID          string `json:"room_id"`
	Slot            int32  `json:"slot"`
	SeedID          string `json:"seed_id"`
	PlantedAtAction int32  `json:"planted_at_action"`
	ReadyAtAction   int32  `json:"ready_at_action"`
	Harvested       bool   `json:"harvested"`
}

type SharedCrystalShard struct {
	WorldID     string `json:"world_id"`
	ShardID     string `json:"shard_id"`
	Biome       string `json:"biome"`
	Collected   bool   `json:"collected"`
	CollectedAt int32  `json:"collected_at"`
}

type SharedDeathPile struct {
	ID        pgtype.UUID        `json:"id"`
	WorldID   string             `json:"world_id"`
	RoomID    string             `json:"room_id"`
	ItemID    string             `json:"item_id"`
	ItemName  string             `json:"item_name"`
	ItemDesc  string             `json:"item_desc"`
	DroppedAt pgtype.Timestamptz `json:"dropped_at"`
}

type SharedEnchant struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
	EnchantID string      `json:"enchant_id"`
	Level     int32       `json:"level"`
	AppliedAt int32       `json:"applied_at"`
}

type SharedEnchantingXp struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Xp        int32       `json:"xp"`
	Level     int32       `json:"level"`
}

type SharedEquippedArmor struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
	ItemName  string      `json:"item_name"`
	Defense   int32       `json:"defense"`
}

type SharedFactionMember struct {
	AccountID     pgtype.UUID `json:"account_id"`
	WorldID       string      `json:"world_id"`
	NpcID         string      `json:"npc_id"`
	NpcName       string      `json:"npc_name"`
	NpcDesc       pgtype.Text `json:"npc_desc"`
	Role          string      `json:"role"`
	StationedRoom pgtype.Text `json:"stationed_room"`
	Loyalty       int32       `json:"loyalty"`
	RecruitedAt   int32       `json:"recruited_at"`
}

type SharedGeneratedContent struct {
	WorldID    string `json:"world_id"`
	PromptHash string `json:"prompt_hash"`
	Type       string `json:"type"`
	YamlBlob   string `json:"yaml_blob"`
	CreatedAt  int32  `json:"created_at"`
}

type SharedHideoutUpgrade struct {
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
	UpgradeID   string      `json:"upgrade_id"`
	InstalledAt int32       `json:"installed_at"`
}

type SharedInventory struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
	ItemName  string      `json:"item_name"`
	ItemDesc  string      `json:"item_desc"`
}

type SharedItemMod struct {
	AccountID    pgtype.UUID `json:"account_id"`
	WorldID      string      `json:"world_id"`
	ItemInstance string      `json:"item_instance"`
	ModID        string      `json:"mod_id"`
	AppliedAt    int32       `json:"applied_at"`
}

type SharedLockState struct {
	WorldID  string `json:"world_id"`
	LockID   string `json:"lock_id"`
	Unlocked bool   `json:"unlocked"`
}

type SharedNpcMemory struct {
	WorldID string `json:"world_id"`
	NpcID   string `json:"npc_id"`
	Action  string `json:"action"`
	Ts      int32  `json:"ts"`
}

type SharedNpcState struct {
	WorldID   string             `json:"world_id"`
	NpcID     string             `json:"npc_id"`
	RoomID    string             `json:"room_id"`
	Hp        int32              `json:"hp"`
	Alive     bool               `json:"alive"`
	RespawnAt pgtype.Timestamptz `json:"respawn_at"`
}

type SharedPlayerAction struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Count     int32       `json:"count"`
}

type SharedPlayerAugment struct {
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
	Skill       string      `json:"skill"`
	Bonus       int32       `json:"bonus"`
	InstalledAt int32       `json:"installed_at"`
}

type SharedPlayerCredit struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Credits   int32       `json:"credits"`
}

type SharedPlayerFaction struct {
	AccountID     pgtype.UUID `json:"account_id"`
	WorldID       string      `json:"world_id"`
	FactionID     string      `json:"faction_id"`
	FactionName   string      `json:"faction_name"`
	Agenda        pgtype.Text `json:"agenda"`
	HideoutRoomID pgtype.Text `json:"hideout_room_id"`
	Credits       int32       `json:"credits"`
	CreatedAt     int32       `json:"created_at"`
}

type SharedPlayerFlag struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Flag      string      `json:"flag"`
}

type SharedPlayerReputation struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Faction   string      `json:"faction"`
	Value     int32       `json:"value"`
}

type SharedPlayerSkill struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Skill     string      `json:"skill"`
	Level     int32       `json:"level"`
	Xp        int32       `json:"xp"`
}

type SharedPlayerState struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	RoomID    string      `json:"room_id"`
	Hp        int32       `json:"hp"`
	MaxHp     int32       `json:"max_hp"`
	Credits   int32       `json:"credits"`
}

type SharedPlayerStealth struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Level     int32       `json:"level"`
	Disguise  string      `json:"disguise"`
}

type SharedQuest struct {
	ID             string      `json:"id"`
	AccountID      pgtype.UUID `json:"account_id"`
	WorldID        string      `json:"world_id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	ObjType        string      `json:"obj_type"`
	ObjTarget      string      `json:"obj_target"`
	ObjRoom        pgtype.Text `json:"obj_room"`
	ObjCount       int32       `json:"obj_count"`
	ObjProgress    int32       `json:"obj_progress"`
	RewardCredits  int32       `json:"reward_credits"`
	RewardXpSkill  pgtype.Text `json:"reward_xp_skill"`
	RewardXpAmount int32       `json:"reward_xp_amount"`
	RewardItemID   pgtype.Text `json:"reward_item_id"`
	RewardItemName pgtype.Text `json:"reward_item_name"`
	RewardItemDesc pgtype.Text `json:"reward_item_desc"`
	GiverNpcID     pgtype.Text `json:"giver_npc_id"`
	AcceptedAt     int32       `json:"accepted_at"`
	NextQuestID    string      `json:"next_quest_id"`
}

type SharedResource struct {
	WorldID    string             `json:"world_id"`
	ResourceID string             `json:"resource_id"`
	RoomID     string             `json:"room_id"`
	Depleted   bool               `json:"depleted"`
	RespawnAt  pgtype.Timestamptz `json:"respawn_at"`
}

type SharedSystemState struct {
	WorldID        string `json:"world_id"`
	SystemID       string `json:"system_id"`
	Hacked         bool   `json:"hacked"`
	IntrusionLevel int32  `json:"intrusion_level"`
	AlertLevel     int32  `json:"alert_level"`
}

type SharedTakenRoomItem struct {
	WorldID string             `json:"world_id"`
	RoomID  string             `json:"room_id"`
	ItemID  string             `json:"item_id"`
	TakenBy pgtype.UUID        `json:"taken_by"`
	TakenAt pgtype.Timestamptz `json:"taken_at"`
}

type SharedUnlockedRecipe struct {
	AccountID  pgtype.UUID `json:"account_id"`
	WorldID    string      `json:"world_id"`
	RecipeID   string      `json:"recipe_id"`
	UnlockedAt int32       `json:"unlocked_at"`
}

type SharedVisited struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	RoomID    string      `json:"room_id"`
}

type SharedVulnWindow struct {
	WorldID       string `json:"world_id"`
	SystemID      string `json:"system_id"`
	Bonus         int32  `json:"bonus"`
	ExpiresAction int32  `json:"expires_action"`
}

type SharedWeatherState struct {
	WorldID       string `json:"world_id"`
	Biome         string `json:"biome"`
	Condition     string `json:"condition"`
	ExpiresAction int32  `json:"expires_action"`
}

type SharedWorldEvent struct {
	ID             string      `json:"id"`
	WorldID        string      `json:"world_id"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	TargetRoom     string      `json:"target_room"`
	Faction        pgtype.Text `json:"faction"`
	PayoutCredits  int32       `json:"payout_credits"`
	PayoutItemID   pgtype.Text `json:"payout_item_id"`
	PayoutItemName pgtype.Text `json:"payout_item_name"`
	PayoutItemDesc pgtype.Text `json:"payout_item_desc"`
	Status         string      `json:"status"`
	ExpiresActions int32       `json:"expires_actions"`
	CreatedActions int32       `json:"created_actions"`
	CreatedAt      int32       `json:"created_at"`
}
