// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shared.sql

package pgq

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptSharedQuest = `-- name: AcceptSharedQuest :exec

INSERT INTO shared_quests
 (id, account_id, world_id, title, description, status, obj_type, obj_target, obj_room,
  obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
  reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
  next_quest_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
ON CONFLICT (id, account_id, world_id) DO NOTHING
`

type AcceptSharedQuestParams struct {
	ID             string      `json:"id"`
	AccountID      pgtype.UUID `json:"account_id"`
	WorldID        string      `json:"world_id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	ObjType        string      `json:"obj_type"`
	ObjTarget      string      `json:"obj_target"`
	ObjRoom        pgtype.Text `json:"obj_room"`
	ObjCount       int32       `json:"obj_count"`
	ObjProgress    int32       `json:"obj_progress"`
	RewardCredits  int32       `json:"reward_credits"`
	RewardXpSkill  pgtype.Text `json:"reward_xp_skill"`
	RewardXpAmount int32       `json:"reward_xp_amount"`
	RewardItemID   pgtype.Text `json:"reward_item_id"`
	RewardItemName pgtype.Text `json:"reward_item_name"`
	RewardItemDesc pgtype.Text `json:"reward_item_desc"`
	GiverNpcID     pgtype.Text `json:"giver_npc_id"`
	AcceptedAt     int32       `json:"accepted_at"`
	NextQuestID    string      `json:"next_quest_id"`
}

// ===================== Quests =====================
func (q *Queries) AcceptSharedQuest(ctx context.Context, arg AcceptSharedQuestParams) error {
	_, err := q.db.Exec(ctx, acceptSharedQuest,
		arg.ID,
		arg.AccountID,
		arg.WorldID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ObjType,
		arg.ObjTarget,
		arg.ObjRoom,
		arg.ObjCount,
		arg.ObjProgress,
		arg.RewardCredits,
		arg.RewardXpSkill,
		arg.RewardXpAmount,
		arg.RewardItemID,
		arg.RewardItemName,
		arg.RewardItemDesc,
		arg.GiverNpcID,
		arg.AcceptedAt,
		arg.NextQuestID,
	)
	return err
}

const addSharedCredits = `-- name: AddSharedCredits :exec
INSERT INTO shared_player_credits (account_id, world_id, credits)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, world_id)
DO UPDATE SET credits = shared_player_credits.credits + EXCLUDED.credits
`

type AddSharedCreditsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Credits   int32       `json:"credits"`
}

func (q *Queries) AddSharedCredits(ctx context.Context, arg AddSharedCreditsParams) error {
	_, err := q.db.Exec(ctx, addSharedCredits, arg.AccountID, arg.WorldID, arg.Credits)
	return err
}

const addSharedEnchantingXP = `-- name: AddSharedEnchantingXP :exec
INSERT INTO shared_enchanting_xp (account_id, world_id, xp, level)
VALUES ($1, $2, $3, 1)
ON CONFLICT (account_id, world_id)
DO UPDATE SET xp = shared_enchanting_xp.xp + EXCLUDED.xp,
             level = LEAST(GREATEST(1, (shared_enchanting_xp.xp + EXCLUDED.xp) / 100), 30)
`

type AddSharedEnchantingXPParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Xp        int32       `json:"xp"`
}

func (q *Queries) AddSharedEnchantingXP(ctx context.Context, arg AddSharedEnchantingXPParams) error {
	_, err := q.db.Exec(ctx, addSharedEnchantingXP, arg.AccountID, arg.WorldID, arg.Xp)
	return err
}

const addSharedItem = `-- name: AddSharedItem :exec
INSERT INTO shared_inventory (account_id, world_id, item_id, item_name, item_desc)
VALUES ($1, $2, $3, $4, $5)
`

type AddSharedItemParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
	ItemName  string      `json:"item_name"`
	ItemDesc  string      `json:"item_desc"`
}

func (q *Queries) AddSharedItem(ctx context.Context, arg AddSharedItemParams) error {
	_, err := q.db.Exec(ctx, addSharedItem,
		arg.AccountID,
		arg.WorldID,
		arg.ItemID,
		arg.ItemName,
		arg.ItemDesc,
	)
	return err
}

const anySharedDeathPile = `-- name: AnySharedDeathPile :one
SELECT room_id, COUNT(*) as count FROM shared_death_pile
WHERE world_id = $1
GROUP BY room_id ORDER BY MAX(dropped_at) DESC LIMIT 1
`

type AnySharedDeathPileRow struct {
	RoomID string `json:"room_id"`
	Count  int64  `json:"count"`
}

func (q *Queries) AnySharedDeathPile(ctx context.Context, worldID string) (AnySharedDeathPileRow, error) {
	row := q.db.QueryRow(ctx, anySharedDeathPile, worldID)
	var i AnySharedDeathPileRow
	err := row.Scan(&i.RoomID, &i.Count)
	return i, err
}

const applySharedEnchant = `-- name: ApplySharedEnchant :exec

INSERT INTO shared_enchants (account_id, world_id, item_id, enchant_id, level, applied_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, world_id, item_id, enchant_id)
DO UPDATE SET level = EXCLUDED.level, applied_at = EXCLUDED.applied_at
`

type ApplySharedEnchantParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
	EnchantID string      `json:"enchant_id"`
	Level     int32       `json:"level"`
	AppliedAt int32       `json:"applied_at"`
}

// ===================== Enchanting =====================
func (q *Queries) ApplySharedEnchant(ctx context.Context, arg ApplySharedEnchantParams) error {
	_, err := q.db.Exec(ctx, applySharedEnchant,
		arg.AccountID,
		arg.WorldID,
		arg.ItemID,
		arg.EnchantID,
		arg.Level,
		arg.AppliedAt,
	)
	return err
}

const bumpSharedActions = `-- name: BumpSharedActions :exec

INSERT INTO shared_player_actions (account_id, world_id, count)
VALUES ($1, $2, 1)
ON CONFLICT (account_id, world_id)
DO UPDATE SET count = shared_player_actions.count + 1
`

type BumpSharedActionsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

// ===================== Mining / Actions =====================
func (q *Queries) BumpSharedActions(ctx context.Context, arg BumpSharedActionsParams) error {
	_, err := q.db.Exec(ctx, bumpSharedActions, arg.AccountID, arg.WorldID)
	return err
}

const clearSharedInventory = `-- name: ClearSharedInventory :exec
DELETE FROM shared_inventory
WHERE account_id = $1 AND world_id = $2
`

type ClearSharedInventoryParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) ClearSharedInventory(ctx context.Context, arg ClearSharedInventoryParams) error {
	_, err := q.db.Exec(ctx, clearSharedInventory, arg.AccountID, arg.WorldID)
	return err
}

const completeSharedEvent = `-- name: CompleteSharedEvent :exec
UPDATE shared_world_events SET status = 'completed' WHERE id = $1 AND world_id = $2
`

type CompleteSharedEventParams struct {
	ID      string `json:"id"`
	WorldID string `json:"world_id"`
}

func (q *Queries) CompleteSharedEvent(ctx context.Context, arg CompleteSharedEventParams) error {
	_, err := q.db.Exec(ctx, completeSharedEvent, arg.ID, arg.WorldID)
	return err
}

const completeSharedQuest = `-- name: CompleteSharedQuest :exec
UPDATE shared_quests SET status = 'completed'
WHERE id = $1 AND account_id = $2 AND world_id = $3
`

type CompleteSharedQuestParams struct {
	ID        string      `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) CompleteSharedQuest(ctx context.Context, arg CompleteSharedQuestParams) error {
	_, err := q.db.Exec(ctx, completeSharedQuest, arg.ID, arg.AccountID, arg.WorldID)
	return err
}

const countSharedActiveBaseRaids = `-- name: CountSharedActiveBaseRaids :one
SELECT COUNT(*) FROM shared_world_events
WHERE world_id = $1 AND type = 'base-raid' AND target_room = $2 AND status = 'active'
`

type CountSharedActiveBaseRaidsParams struct {
	WorldID    string `json:"world_id"`
	TargetRoom string `json:"target_room"`
}

func (q *Queries) CountSharedActiveBaseRaids(ctx context.Context, arg CountSharedActiveBaseRaidsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedActiveBaseRaids, arg.WorldID, arg.TargetRoom)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedBuilds = `-- name: CountSharedBuilds :one
SELECT COUNT(*) FROM shared_builds
WHERE world_id = $1 AND room_id = $2
`

type CountSharedBuildsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) CountSharedBuilds(ctx context.Context, arg CountSharedBuildsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedBuilds, arg.WorldID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedBuildsByType = `-- name: CountSharedBuildsByType :one
SELECT COUNT(*) FROM shared_builds
WHERE world_id = $1 AND room_id = $2 AND build_id = $3
`

type CountSharedBuildsByTypeParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
	BuildID string `json:"build_id"`
}

func (q *Queries) CountSharedBuildsByType(ctx context.Context, arg CountSharedBuildsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedBuildsByType, arg.WorldID, arg.RoomID, arg.BuildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedChestInRoom = `-- name: CountSharedChestInRoom :one
SELECT COUNT(*) FROM shared_builds
WHERE world_id = $1 AND room_id = $2 AND build_id = 'chest'
`

type CountSharedChestInRoomParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) CountSharedChestInRoom(ctx context.Context, arg CountSharedChestInRoomParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedChestInRoom, arg.WorldID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedChestItems = `-- name: CountSharedChestItems :one
SELECT COUNT(*) FROM shared_chests
WHERE world_id = $1 AND room_id = $2
`

type CountSharedChestItemsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) CountSharedChestItems(ctx context.Context, arg CountSharedChestItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedChestItems, arg.WorldID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedCollectedShards = `-- name: CountSharedCollectedShards :one
SELECT COUNT(*) FROM shared_crystal_shards
WHERE world_id = $1 AND collected = TRUE
`

func (q *Queries) CountSharedCollectedShards(ctx context.Context, worldID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedCollectedShards, worldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedEnchantingTable = `-- name: CountSharedEnchantingTable :one
SELECT COUNT(*) FROM shared_builds
WHERE world_id = $1 AND room_id = $2 AND build_id = 'enchanting-table'
`

type CountSharedEnchantingTableParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) CountSharedEnchantingTable(ctx context.Context, arg CountSharedEnchantingTableParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedEnchantingTable, arg.WorldID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedReadyCrops = `-- name: CountSharedReadyCrops :one
SELECT COUNT(*) FROM shared_crops
WHERE world_id = $1 AND room_id = $2 AND seed_id = $3 AND ready_at_action <= $4 AND harvested = FALSE
`

type CountSharedReadyCropsParams struct {
	WorldID       string `json:"world_id"`
	RoomID        string `json:"room_id"`
	SeedID        string `json:"seed_id"`
	ReadyAtAction int32  `json:"ready_at_action"`
}

func (q *Queries) CountSharedReadyCrops(ctx context.Context, arg CountSharedReadyCropsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedReadyCrops,
		arg.WorldID,
		arg.RoomID,
		arg.SeedID,
		arg.ReadyAtAction,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedTotalShards = `-- name: CountSharedTotalShards :one
SELECT COUNT(*) FROM shared_crystal_shards
WHERE world_id = $1
`

func (q *Queries) CountSharedTotalShards(ctx context.Context, worldID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedTotalShards, worldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSharedFaction = `-- name: CreateSharedFaction :exec

INSERT INTO shared_player_faction (account_id, world_id, faction_id, faction_name, agenda, hideout_room_id, credits, created_at)
VALUES ($1, $2, $3, $4, $5, '', 0, $6)
`

type CreateSharedFactionParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
	FactionID   string      `json:"faction_id"`
	FactionName string      `json:"faction_name"`
	Agenda      pgtype.Text `json:"agenda"`
	CreatedAt   int32       `json:"created_at"`
}

// ===================== Factions =====================
func (q *Queries) CreateSharedFaction(ctx context.Context, arg CreateSharedFactionParams) error {
	_, err := q.db.Exec(ctx, createSharedFaction,
		arg.AccountID,
		arg.WorldID,
		arg.FactionID,
		arg.FactionName,
		arg.Agenda,
		arg.CreatedAt,
	)
	return err
}

const deductSharedEnchantingXP = `-- name: DeductSharedEnchantingXP :exec
UPDATE shared_enchanting_xp SET xp = xp - $1
WHERE account_id = $2 AND world_id = $3
`

type DeductSharedEnchantingXPParams struct {
	Xp        int32       `json:"xp"`
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) DeductSharedEnchantingXP(ctx context.Context, arg DeductSharedEnchantingXPParams) error {
	_, err := q.db.Exec(ctx, deductSharedEnchantingXP, arg.Xp, arg.AccountID, arg.WorldID)
	return err
}

const deleteSharedChestItem = `-- name: DeleteSharedChestItem :exec
DELETE FROM shared_chests
WHERE world_id = $1 AND room_id = $2 AND item_id = $3
`

type DeleteSharedChestItemParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
	ItemID  string `json:"item_id"`
}

func (q *Queries) DeleteSharedChestItem(ctx context.Context, arg DeleteSharedChestItemParams) error {
	_, err := q.db.Exec(ctx, deleteSharedChestItem, arg.WorldID, arg.RoomID, arg.ItemID)
	return err
}

const deleteSharedDeathPile = `-- name: DeleteSharedDeathPile :exec
DELETE FROM shared_death_pile
WHERE world_id = $1 AND room_id = $2
`

type DeleteSharedDeathPileParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) DeleteSharedDeathPile(ctx context.Context, arg DeleteSharedDeathPileParams) error {
	_, err := q.db.Exec(ctx, deleteSharedDeathPile, arg.WorldID, arg.RoomID)
	return err
}

const deleteSharedEquippedArmor = `-- name: DeleteSharedEquippedArmor :exec
DELETE FROM shared_equipped_armor
WHERE account_id = $1 AND world_id = $2
`

type DeleteSharedEquippedArmorParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) DeleteSharedEquippedArmor(ctx context.Context, arg DeleteSharedEquippedArmorParams) error {
	_, err := q.db.Exec(ctx, deleteSharedEquippedArmor, arg.AccountID, arg.WorldID)
	return err
}

const deleteSharedVulnWindow = `-- name: DeleteSharedVulnWindow :exec
DELETE FROM shared_vuln_windows
WHERE world_id = $1 AND system_id = $2
`

type DeleteSharedVulnWindowParams struct {
	WorldID  string `json:"world_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) DeleteSharedVulnWindow(ctx context.Context, arg DeleteSharedVulnWindowParams) error {
	_, err := q.db.Exec(ctx, deleteSharedVulnWindow, arg.WorldID, arg.SystemID)
	return err
}

const depleteSharedResource = `-- name: DepleteSharedResource :exec
INSERT INTO shared_resources (world_id, resource_id, room_id, depleted, respawn_at)
VALUES ($1, $2, $3, TRUE, $4)
ON CONFLICT (world_id, resource_id)
DO UPDATE SET depleted = TRUE, respawn_at = EXCLUDED.respawn_at
`

type DepleteSharedResourceParams struct {
	WorldID    string             `json:"world_id"`
	ResourceID string             `json:"resource_id"`
	RoomID     string             `json:"room_id"`
	RespawnAt  pgtype.Timestamptz `json:"respawn_at"`
}

func (q *Queries) DepleteSharedResource(ctx context.Context, arg DepleteSharedResourceParams) error {
	_, err := q.db.Exec(ctx, depleteSharedResource,
		arg.WorldID,
		arg.ResourceID,
		arg.RoomID,
		arg.RespawnAt,
	)
	return err
}

const expireSharedOldEvents = `-- name: ExpireSharedOldEvents :execresult
UPDATE shared_world_events SET status = 'expired'
WHERE world_id = $1 AND status = 'active' AND (created_actions + expires_actions) <= $2
`

type ExpireSharedOldEventsParams struct {
	WorldID        string `json:"world_id"`
	CreatedActions int32  `json:"created_actions"`
}

func (q *Queries) ExpireSharedOldEvents(ctx context.Context, arg ExpireSharedOldEventsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, expireSharedOldEvents, arg.WorldID, arg.CreatedActions)
}

const failSharedQuest = `-- name: FailSharedQuest :exec
UPDATE shared_quests SET status = 'failed'
WHERE id = $1 AND account_id = $2 AND world_id = $3
`

type FailSharedQuestParams struct {
	ID        string      `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) FailSharedQuest(ctx context.Context, arg FailSharedQuestParams) error {
	_, err := q.db.Exec(ctx, failSharedQuest, arg.ID, arg.AccountID, arg.WorldID)
	return err
}

const getSharedActionCount = `-- name: GetSharedActionCount :one
SELECT count
FROM shared_player_actions
WHERE account_id = $1 AND world_id = $2
`

type GetSharedActionCountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) GetSharedActionCount(ctx context.Context, arg GetSharedActionCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSharedActionCount, arg.AccountID, arg.WorldID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getSharedActiveArena = `-- name: GetSharedActiveArena :one
SELECT id, game_type, wave, enemies, started_at
FROM shared_arena_sessions
WHERE account_id = $1 AND world_id = $2
ORDER BY started_at DESC
LIMIT 1
`

type GetSharedActiveArenaParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedActiveArenaRow struct {
	ID        pgtype.UUID        `json:"id"`
	GameType  string             `json:"game_type"`
	Wave      int32              `json:"wave"`
	Enemies   string             `json:"enemies"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) GetSharedActiveArena(ctx context.Context, arg GetSharedActiveArenaParams) (GetSharedActiveArenaRow, error) {
	row := q.db.QueryRow(ctx, getSharedActiveArena, arg.AccountID, arg.WorldID)
	var i GetSharedActiveArenaRow
	err := row.Scan(
		&i.ID,
		&i.GameType,
		&i.Wave,
		&i.Enemies,
		&i.StartedAt,
	)
	return i, err
}

const getSharedActiveQuests = `-- name: GetSharedActiveQuests :many
SELECT id, title, description, status, obj_type, obj_target, obj_room,
       obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
       reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
       next_quest_id
FROM shared_quests
WHERE account_id = $1 AND world_id = $2 AND status = 'active'
`

type GetSharedActiveQuestsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedActiveQuestsRow struct {
	ID             string      `json:"id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	ObjType        string      `json:"obj_type"`
	ObjTarget      string      `json:"obj_target"`
	ObjRoom        pgtype.Text `json:"obj_room"`
	ObjCount       int32       `json:"obj_count"`
	ObjProgress    int32       `json:"obj_progress"`
	RewardCredits  int32       `json:"reward_credits"`
	RewardXpSkill  pgtype.Text `json:"reward_xp_skill"`
	RewardXpAmount int32       `json:"reward_xp_amount"`
	RewardItemID   pgtype.Text `json:"reward_item_id"`
	RewardItemName pgtype.Text `json:"reward_item_name"`
	RewardItemDesc pgtype.Text `json:"reward_item_desc"`
	GiverNpcID     pgtype.Text `json:"giver_npc_id"`
	AcceptedAt     int32       `json:"accepted_at"`
	NextQuestID    string      `json:"next_quest_id"`
}

func (q *Queries) GetSharedActiveQuests(ctx context.Context, arg GetSharedActiveQuestsParams) ([]GetSharedActiveQuestsRow, error) {
	rows, err := q.db.Query(ctx, getSharedActiveQuests, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedActiveQuestsRow{}
	for rows.Next() {
		var i GetSharedActiveQuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ObjType,
			&i.ObjTarget,
			&i.ObjRoom,
			&i.ObjCount,
			&i.ObjProgress,
			&i.RewardCredits,
			&i.RewardXpSkill,
			&i.RewardXpAmount,
			&i.RewardItemID,
			&i.RewardItemName,
			&i.RewardItemDesc,
			&i.GiverNpcID,
			&i.AcceptedAt,
			&i.NextQuestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedAugment = `-- name: GetSharedAugment :one
SELECT bonus, installed_at
FROM shared_player_augments
WHERE account_id = $1 AND world_id = $2 AND skill = $3
`

type GetSharedAugmentParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Skill     string      `json:"skill"`
}

type GetSharedAugmentRow struct {
	Bonus       int32 `json:"bonus"`
	InstalledAt int32 `json:"installed_at"`
}

func (q *Queries) GetSharedAugment(ctx context.Context, arg GetSharedAugmentParams) (GetSharedAugmentRow, error) {
	row := q.db.QueryRow(ctx, getSharedAugment, arg.AccountID, arg.WorldID, arg.Skill)
	var i GetSharedAugmentRow
	err := row.Scan(&i.Bonus, &i.InstalledAt)
	return i, err
}

const getSharedBounty = `-- name: GetSharedBounty :one
SELECT npc_id, created_at FROM shared_bounties
WHERE world_id = $1 AND room_id = $2
`

type GetSharedBountyParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

type GetSharedBountyRow struct {
	NpcID     string `json:"npc_id"`
	CreatedAt int32  `json:"created_at"`
}

func (q *Queries) GetSharedBounty(ctx context.Context, arg GetSharedBountyParams) (GetSharedBountyRow, error) {
	row := q.db.QueryRow(ctx, getSharedBounty, arg.WorldID, arg.RoomID)
	var i GetSharedBountyRow
	err := row.Scan(&i.NpcID, &i.CreatedAt)
	return i, err
}

const getSharedChestItems = `-- name: GetSharedChestItems :many
SELECT item_id, item_name
FROM shared_chests
WHERE world_id = $1 AND room_id = $2
`

type GetSharedChestItemsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

type GetSharedChestItemsRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
}

func (q *Queries) GetSharedChestItems(ctx context.Context, arg GetSharedChestItemsParams) ([]GetSharedChestItemsRow, error) {
	rows, err := q.db.Query(ctx, getSharedChestItems, arg.WorldID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedChestItemsRow{}
	for rows.Next() {
		var i GetSharedChestItemsRow
		if err := rows.Scan(&i.ItemID, &i.ItemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedCredits = `-- name: GetSharedCredits :one

SELECT credits
FROM shared_player_credits
WHERE account_id = $1 AND world_id = $2
`

type GetSharedCreditsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

// ===================== Credits =====================
func (q *Queries) GetSharedCredits(ctx context.Context, arg GetSharedCreditsParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSharedCredits, arg.AccountID, arg.WorldID)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const getSharedDeathPile = `-- name: GetSharedDeathPile :many
SELECT item_id, item_name, item_desc
FROM shared_death_pile
WHERE world_id = $1 AND room_id = $2
`

type GetSharedDeathPileParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

type GetSharedDeathPileRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) GetSharedDeathPile(ctx context.Context, arg GetSharedDeathPileParams) ([]GetSharedDeathPileRow, error) {
	rows, err := q.db.Query(ctx, getSharedDeathPile, arg.WorldID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedDeathPileRow{}
	for rows.Next() {
		var i GetSharedDeathPileRow
		if err := rows.Scan(&i.ItemID, &i.ItemName, &i.ItemDesc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedEnchantingXP = `-- name: GetSharedEnchantingXP :one
SELECT xp, level
FROM shared_enchanting_xp
WHERE account_id = $1 AND world_id = $2
`

type GetSharedEnchantingXPParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedEnchantingXPRow struct {
	Xp    int32 `json:"xp"`
	Level int32 `json:"level"`
}

func (q *Queries) GetSharedEnchantingXP(ctx context.Context, arg GetSharedEnchantingXPParams) (GetSharedEnchantingXPRow, error) {
	row := q.db.QueryRow(ctx, getSharedEnchantingXP, arg.AccountID, arg.WorldID)
	var i GetSharedEnchantingXPRow
	err := row.Scan(&i.Xp, &i.Level)
	return i, err
}

const getSharedEquippedArmor = `-- name: GetSharedEquippedArmor :one

SELECT item_id, item_name, defense
FROM shared_equipped_armor
WHERE account_id = $1 AND world_id = $2
`

type GetSharedEquippedArmorParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedEquippedArmorRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	Defense  int32  `json:"defense"`
}

// ===================== Equipped Armor =====================
func (q *Queries) GetSharedEquippedArmor(ctx context.Context, arg GetSharedEquippedArmorParams) (GetSharedEquippedArmorRow, error) {
	row := q.db.QueryRow(ctx, getSharedEquippedArmor, arg.AccountID, arg.WorldID)
	var i GetSharedEquippedArmorRow
	err := row.Scan(&i.ItemID, &i.ItemName, &i.Defense)
	return i, err
}

const getSharedEvent = `-- name: GetSharedEvent :one
SELECT id, type, title, description, target_room, faction,
       payout_credits, payout_item_id, payout_item_name, payout_item_desc,
       status, expires_actions, created_actions, created_at
FROM shared_world_events WHERE id = $1 AND world_id = $2
`

type GetSharedEventParams struct {
	ID      string `json:"id"`
	WorldID string `json:"world_id"`
}

type GetSharedEventRow struct {
	ID             string      `json:"id"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	TargetRoom     string      `json:"target_room"`
	Faction        pgtype.Text `json:"faction"`
	PayoutCredits  int32       `json:"payout_credits"`
	PayoutItemID   pgtype.Text `json:"payout_item_id"`
	PayoutItemName pgtype.Text `json:"payout_item_name"`
	PayoutItemDesc pgtype.Text `json:"payout_item_desc"`
	Status         string      `json:"status"`
	ExpiresActions int32       `json:"expires_actions"`
	CreatedActions int32       `json:"created_actions"`
	CreatedAt      int32       `json:"created_at"`
}

func (q *Queries) GetSharedEvent(ctx context.Context, arg GetSharedEventParams) (GetSharedEventRow, error) {
	row := q.db.QueryRow(ctx, getSharedEvent, arg.ID, arg.WorldID)
	var i GetSharedEventRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.TargetRoom,
		&i.Faction,
		&i.PayoutCredits,
		&i.PayoutItemID,
		&i.PayoutItemName,
		&i.PayoutItemDesc,
		&i.Status,
		&i.ExpiresActions,
		&i.CreatedActions,
		&i.CreatedAt,
	)
	return i, err
}

const getSharedFaction = `-- name: GetSharedFaction :one
SELECT faction_id, faction_name, agenda, hideout_room_id, credits, created_at
FROM shared_player_faction
WHERE account_id = $1 AND world_id = $2
`

type GetSharedFactionParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedFactionRow struct {
	FactionID     string      `json:"faction_id"`
	FactionName   string      `json:"faction_name"`
	Agenda        pgtype.Text `json:"agenda"`
	HideoutRoomID pgtype.Text `json:"hideout_room_id"`
	Credits       int32       `json:"credits"`
	CreatedAt     int32       `json:"created_at"`
}

func (q *Queries) GetSharedFaction(ctx context.Context, arg GetSharedFactionParams) (GetSharedFactionRow, error) {
	row := q.db.QueryRow(ctx, getSharedFaction, arg.AccountID, arg.WorldID)
	var i GetSharedFactionRow
	err := row.Scan(
		&i.FactionID,
		&i.FactionName,
		&i.Agenda,
		&i.HideoutRoomID,
		&i.Credits,
		&i.CreatedAt,
	)
	return i, err
}

const getSharedGeneratedContent = `-- name: GetSharedGeneratedContent :one

SELECT type, yaml_blob, created_at
FROM shared_generated_content
WHERE world_id = $1 AND prompt_hash = $2
`

type GetSharedGeneratedContentParams struct {
	WorldID    string `json:"world_id"`
	PromptHash string `json:"prompt_hash"`
}

type GetSharedGeneratedContentRow struct {
	Type      string `json:"type"`
	YamlBlob  string `json:"yaml_blob"`
	CreatedAt int32  `json:"created_at"`
}

// ===================== Generated Content =====================
func (q *Queries) GetSharedGeneratedContent(ctx context.Context, arg GetSharedGeneratedContentParams) (GetSharedGeneratedContentRow, error) {
	row := q.db.QueryRow(ctx, getSharedGeneratedContent, arg.WorldID, arg.PromptHash)
	var i GetSharedGeneratedContentRow
	err := row.Scan(&i.Type, &i.YamlBlob, &i.CreatedAt)
	return i, err
}

const getSharedItemMod = `-- name: GetSharedItemMod :one
SELECT mod_id, applied_at
FROM shared_item_mods
WHERE account_id = $1 AND world_id = $2 AND item_instance = $3
`

type GetSharedItemModParams struct {
	AccountID    pgtype.UUID `json:"account_id"`
	WorldID      string      `json:"world_id"`
	ItemInstance string      `json:"item_instance"`
}

type GetSharedItemModRow struct {
	ModID     string `json:"mod_id"`
	AppliedAt int32  `json:"applied_at"`
}

func (q *Queries) GetSharedItemMod(ctx context.Context, arg GetSharedItemModParams) (GetSharedItemModRow, error) {
	row := q.db.QueryRow(ctx, getSharedItemMod, arg.AccountID, arg.WorldID, arg.ItemInstance)
	var i GetSharedItemModRow
	err := row.Scan(&i.ModID, &i.AppliedAt)
	return i, err
}

const getSharedLockState = `-- name: GetSharedLockState :one

SELECT unlocked
FROM shared_lock_state
WHERE world_id = $1 AND lock_id = $2
`

type GetSharedLockStateParams struct {
	WorldID string `json:"world_id"`
	LockID  string `json:"lock_id"`
}

// ===================== Lock State =====================
func (q *Queries) GetSharedLockState(ctx context.Context, arg GetSharedLockStateParams) (bool, error) {
	row := q.db.QueryRow(ctx, getSharedLockState, arg.WorldID, arg.LockID)
	var unlocked bool
	err := row.Scan(&unlocked)
	return unlocked, err
}

const getSharedMembers = `-- name: GetSharedMembers :many
SELECT npc_id, npc_name, npc_desc, role, stationed_room, loyalty, recruited_at
FROM shared_faction_members
WHERE account_id = $1 AND world_id = $2
`

type GetSharedMembersParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedMembersRow struct {
	NpcID         string      `json:"npc_id"`
	NpcName       string      `json:"npc_name"`
	NpcDesc       pgtype.Text `json:"npc_desc"`
	Role          string      `json:"role"`
	StationedRoom pgtype.Text `json:"stationed_room"`
	Loyalty       int32       `json:"loyalty"`
	RecruitedAt   int32       `json:"recruited_at"`
}

func (q *Queries) GetSharedMembers(ctx context.Context, arg GetSharedMembersParams) ([]GetSharedMembersRow, error) {
	rows, err := q.db.Query(ctx, getSharedMembers, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedMembersRow{}
	for rows.Next() {
		var i GetSharedMembersRow
		if err := rows.Scan(
			&i.NpcID,
			&i.NpcName,
			&i.NpcDesc,
			&i.Role,
			&i.StationedRoom,
			&i.Loyalty,
			&i.RecruitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedNPCMemory = `-- name: GetSharedNPCMemory :one
SELECT ts FROM shared_npc_memory
WHERE world_id = $1 AND npc_id = $2 AND action = $3
`

type GetSharedNPCMemoryParams struct {
	WorldID string `json:"world_id"`
	NpcID   string `json:"npc_id"`
	Action  string `json:"action"`
}

func (q *Queries) GetSharedNPCMemory(ctx context.Context, arg GetSharedNPCMemoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSharedNPCMemory, arg.WorldID, arg.NpcID, arg.Action)
	var ts int32
	err := row.Scan(&ts)
	return ts, err
}

const getSharedNPCState = `-- name: GetSharedNPCState :one

SELECT hp, alive, respawn_at
FROM shared_npc_state
WHERE world_id = $1 AND npc_id = $2
`

type GetSharedNPCStateParams struct {
	WorldID string `json:"world_id"`
	NpcID   string `json:"npc_id"`
}

type GetSharedNPCStateRow struct {
	Hp        int32              `json:"hp"`
	Alive     bool               `json:"alive"`
	RespawnAt pgtype.Timestamptz `json:"respawn_at"`
}

// ===================== NPC State =====================
func (q *Queries) GetSharedNPCState(ctx context.Context, arg GetSharedNPCStateParams) (GetSharedNPCStateRow, error) {
	row := q.db.QueryRow(ctx, getSharedNPCState, arg.WorldID, arg.NpcID)
	var i GetSharedNPCStateRow
	err := row.Scan(&i.Hp, &i.Alive, &i.RespawnAt)
	return i, err
}

const getSharedPlayerState = `-- name: GetSharedPlayerState :one


SELECT room_id, hp, max_hp, credits
FROM shared_player_state
WHERE account_id = $1 AND world_id = $2
`

type GetSharedPlayerStateParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedPlayerStateRow struct {
	RoomID  string `json:"room_id"`
	Hp      int32  `json:"hp"`
	MaxHp   int32  `json:"max_hp"`
	Credits int32  `json:"credits"`
}

// ============================================================
// Shared World Queries (Postgres)
// All queries prefixed with "Shared" to avoid SQLite conflicts.
// ============================================================
// ===================== Player State =====================
func (q *Queries) GetSharedPlayerState(ctx context.Context, arg GetSharedPlayerStateParams) (GetSharedPlayerStateRow, error) {
	row := q.db.QueryRow(ctx, getSharedPlayerState, arg.AccountID, arg.WorldID)
	var i GetSharedPlayerStateRow
	err := row.Scan(
		&i.RoomID,
		&i.Hp,
		&i.MaxHp,
		&i.Credits,
	)
	return i, err
}

const getSharedQuest = `-- name: GetSharedQuest :one
SELECT id, title, description, status, obj_type, obj_target, obj_room,
       obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
       reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
       next_quest_id
FROM shared_quests
WHERE id = $1 AND account_id = $2 AND world_id = $3
`

type GetSharedQuestParams struct {
	ID        string      `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedQuestRow struct {
	ID             string      `json:"id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	ObjType        string      `json:"obj_type"`
	ObjTarget      string      `json:"obj_target"`
	ObjRoom        pgtype.Text `json:"obj_room"`
	ObjCount       int32       `json:"obj_count"`
	ObjProgress    int32       `json:"obj_progress"`
	RewardCredits  int32       `json:"reward_credits"`
	RewardXpSkill  pgtype.Text `json:"reward_xp_skill"`
	RewardXpAmount int32       `json:"reward_xp_amount"`
	RewardItemID   pgtype.Text `json:"reward_item_id"`
	RewardItemName pgtype.Text `json:"reward_item_name"`
	RewardItemDesc pgtype.Text `json:"reward_item_desc"`
	GiverNpcID     pgtype.Text `json:"giver_npc_id"`
	AcceptedAt     int32       `json:"accepted_at"`
	NextQuestID    string      `json:"next_quest_id"`
}

func (q *Queries) GetSharedQuest(ctx context.Context, arg GetSharedQuestParams) (GetSharedQuestRow, error) {
	row := q.db.QueryRow(ctx, getSharedQuest, arg.ID, arg.AccountID, arg.WorldID)
	var i GetSharedQuestRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ObjType,
		&i.ObjTarget,
		&i.ObjRoom,
		&i.ObjCount,
		&i.ObjProgress,
		&i.RewardCredits,
		&i.RewardXpSkill,
		&i.RewardXpAmount,
		&i.RewardItemID,
		&i.RewardItemName,
		&i.RewardItemDesc,
		&i.GiverNpcID,
		&i.AcceptedAt,
		&i.NextQuestID,
	)
	return i, err
}

const getSharedReadyCrops = `-- name: GetSharedReadyCrops :many

SELECT seed_id
FROM shared_crops
WHERE world_id = $1 AND room_id = $2 AND ready_at_action <= $3 AND harvested = FALSE
`

type GetSharedReadyCropsParams struct {
	WorldID       string `json:"world_id"`
	RoomID        string `json:"room_id"`
	ReadyAtAction int32  `json:"ready_at_action"`
}

// ===================== Farming / Crops =====================
func (q *Queries) GetSharedReadyCrops(ctx context.Context, arg GetSharedReadyCropsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getSharedReadyCrops, arg.WorldID, arg.RoomID, arg.ReadyAtAction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var seed_id string
		if err := rows.Scan(&seed_id); err != nil {
			return nil, err
		}
		items = append(items, seed_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedReputation = `-- name: GetSharedReputation :one

SELECT value FROM shared_player_reputation
WHERE account_id = $1 AND world_id = $2 AND faction = $3
`

type GetSharedReputationParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Faction   string      `json:"faction"`
}

// ===================== Reputation =====================
func (q *Queries) GetSharedReputation(ctx context.Context, arg GetSharedReputationParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSharedReputation, arg.AccountID, arg.WorldID, arg.Faction)
	var value int32
	err := row.Scan(&value)
	return value, err
}

const getSharedResourceState = `-- name: GetSharedResourceState :one

SELECT depleted, respawn_at
FROM shared_resources
WHERE world_id = $1 AND resource_id = $2
`

type GetSharedResourceStateParams struct {
	WorldID    string `json:"world_id"`
	ResourceID string `json:"resource_id"`
}

type GetSharedResourceStateRow struct {
	Depleted  bool               `json:"depleted"`
	RespawnAt pgtype.Timestamptz `json:"respawn_at"`
}

// ===================== Resource State =====================
func (q *Queries) GetSharedResourceState(ctx context.Context, arg GetSharedResourceStateParams) (GetSharedResourceStateRow, error) {
	row := q.db.QueryRow(ctx, getSharedResourceState, arg.WorldID, arg.ResourceID)
	var i GetSharedResourceStateRow
	err := row.Scan(&i.Depleted, &i.RespawnAt)
	return i, err
}

const getSharedSkill = `-- name: GetSharedSkill :one

SELECT level, xp
FROM shared_player_skills
WHERE account_id = $1 AND world_id = $2 AND skill = $3
`

type GetSharedSkillParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Skill     string      `json:"skill"`
}

type GetSharedSkillRow struct {
	Level int32 `json:"level"`
	Xp    int32 `json:"xp"`
}

// ===================== Skills =====================
func (q *Queries) GetSharedSkill(ctx context.Context, arg GetSharedSkillParams) (GetSharedSkillRow, error) {
	row := q.db.QueryRow(ctx, getSharedSkill, arg.AccountID, arg.WorldID, arg.Skill)
	var i GetSharedSkillRow
	err := row.Scan(&i.Level, &i.Xp)
	return i, err
}

const getSharedStealth = `-- name: GetSharedStealth :one
SELECT level, disguise
FROM shared_player_stealth
WHERE account_id = $1 AND world_id = $2
`

type GetSharedStealthParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type GetSharedStealthRow struct {
	Level    int32  `json:"level"`
	Disguise string `json:"disguise"`
}

func (q *Queries) GetSharedStealth(ctx context.Context, arg GetSharedStealthParams) (GetSharedStealthRow, error) {
	row := q.db.QueryRow(ctx, getSharedStealth, arg.AccountID, arg.WorldID)
	var i GetSharedStealthRow
	err := row.Scan(&i.Level, &i.Disguise)
	return i, err
}

const getSharedSystemState = `-- name: GetSharedSystemState :one

SELECT hacked, intrusion_level, alert_level
FROM shared_system_state
WHERE world_id = $1 AND system_id = $2
`

type GetSharedSystemStateParams struct {
	WorldID  string `json:"world_id"`
	SystemID string `json:"system_id"`
}

type GetSharedSystemStateRow struct {
	Hacked         bool  `json:"hacked"`
	IntrusionLevel int32 `json:"intrusion_level"`
	AlertLevel     int32 `json:"alert_level"`
}

// ===================== System State =====================
func (q *Queries) GetSharedSystemState(ctx context.Context, arg GetSharedSystemStateParams) (GetSharedSystemStateRow, error) {
	row := q.db.QueryRow(ctx, getSharedSystemState, arg.WorldID, arg.SystemID)
	var i GetSharedSystemStateRow
	err := row.Scan(&i.Hacked, &i.IntrusionLevel, &i.AlertLevel)
	return i, err
}

const getSharedUsedSlots = `-- name: GetSharedUsedSlots :many
SELECT slot FROM shared_crops
WHERE world_id = $1 AND room_id = $2 AND harvested = FALSE
`

type GetSharedUsedSlotsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) GetSharedUsedSlots(ctx context.Context, arg GetSharedUsedSlotsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getSharedUsedSlots, arg.WorldID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var slot int32
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedVulnWindow = `-- name: GetSharedVulnWindow :one
SELECT bonus, expires_action FROM shared_vuln_windows
WHERE world_id = $1 AND system_id = $2
`

type GetSharedVulnWindowParams struct {
	WorldID  string `json:"world_id"`
	SystemID string `json:"system_id"`
}

type GetSharedVulnWindowRow struct {
	Bonus         int32 `json:"bonus"`
	ExpiresAction int32 `json:"expires_action"`
}

func (q *Queries) GetSharedVulnWindow(ctx context.Context, arg GetSharedVulnWindowParams) (GetSharedVulnWindowRow, error) {
	row := q.db.QueryRow(ctx, getSharedVulnWindow, arg.WorldID, arg.SystemID)
	var i GetSharedVulnWindowRow
	err := row.Scan(&i.Bonus, &i.ExpiresAction)
	return i, err
}

const getSharedWeather = `-- name: GetSharedWeather :one

SELECT condition, expires_action
FROM shared_weather_state
WHERE world_id = $1 AND biome = $2
`

type GetSharedWeatherParams struct {
	WorldID string `json:"world_id"`
	Biome   string `json:"biome"`
}

type GetSharedWeatherRow struct {
	Condition     string `json:"condition"`
	ExpiresAction int32  `json:"expires_action"`
}

// ===================== Weather =====================
func (q *Queries) GetSharedWeather(ctx context.Context, arg GetSharedWeatherParams) (GetSharedWeatherRow, error) {
	row := q.db.QueryRow(ctx, getSharedWeather, arg.WorldID, arg.Biome)
	var i GetSharedWeatherRow
	err := row.Scan(&i.Condition, &i.ExpiresAction)
	return i, err
}

const getSharedWeatherCondition = `-- name: GetSharedWeatherCondition :one
SELECT condition
FROM shared_weather_state
WHERE world_id = $1 AND biome = $2
`

type GetSharedWeatherConditionParams struct {
	WorldID string `json:"world_id"`
	Biome   string `json:"biome"`
}

func (q *Queries) GetSharedWeatherCondition(ctx context.Context, arg GetSharedWeatherConditionParams) (string, error) {
	row := q.db.QueryRow(ctx, getSharedWeatherCondition, arg.WorldID, arg.Biome)
	var condition string
	err := row.Scan(&condition)
	return condition, err
}

const harvestSharedCrops = `-- name: HarvestSharedCrops :exec
UPDATE shared_crops SET harvested = TRUE
WHERE world_id = $1 AND room_id = $2 AND seed_id = $3 AND ready_at_action <= $4 AND harvested = FALSE
`

type HarvestSharedCropsParams struct {
	WorldID       string `json:"world_id"`
	RoomID        string `json:"room_id"`
	SeedID        string `json:"seed_id"`
	ReadyAtAction int32  `json:"ready_at_action"`
}

func (q *Queries) HarvestSharedCrops(ctx context.Context, arg HarvestSharedCropsParams) error {
	_, err := q.db.Exec(ctx, harvestSharedCrops,
		arg.WorldID,
		arg.RoomID,
		arg.SeedID,
		arg.ReadyAtAction,
	)
	return err
}

const hasSharedPlayerFlag = `-- name: HasSharedPlayerFlag :one
SELECT COUNT(*) FROM shared_player_flags
WHERE account_id = $1 AND world_id = $2 AND flag = $3
`

type HasSharedPlayerFlagParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Flag      string      `json:"flag"`
}

func (q *Queries) HasSharedPlayerFlag(ctx context.Context, arg HasSharedPlayerFlagParams) (int64, error) {
	row := q.db.QueryRow(ctx, hasSharedPlayerFlag, arg.AccountID, arg.WorldID, arg.Flag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasSharedVisited = `-- name: HasSharedVisited :one
SELECT room_id FROM shared_visited
WHERE account_id = $1 AND world_id = $2 AND room_id = $3
`

type HasSharedVisitedParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	RoomID    string      `json:"room_id"`
}

func (q *Queries) HasSharedVisited(ctx context.Context, arg HasSharedVisitedParams) (string, error) {
	row := q.db.QueryRow(ctx, hasSharedVisited, arg.AccountID, arg.WorldID, arg.RoomID)
	var room_id string
	err := row.Scan(&room_id)
	return room_id, err
}

const incrementSharedAlert = `-- name: IncrementSharedAlert :exec
INSERT INTO shared_system_state (world_id, system_id, hacked, intrusion_level, alert_level)
VALUES ($1, $2, FALSE, 0, 1)
ON CONFLICT (world_id, system_id)
DO UPDATE SET alert_level = shared_system_state.alert_level + 1
`

type IncrementSharedAlertParams struct {
	WorldID  string `json:"world_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) IncrementSharedAlert(ctx context.Context, arg IncrementSharedAlertParams) error {
	_, err := q.db.Exec(ctx, incrementSharedAlert, arg.WorldID, arg.SystemID)
	return err
}

const insertSharedBounty = `-- name: InsertSharedBounty :exec

INSERT INTO shared_bounties (world_id, room_id, npc_id, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (world_id, room_id)
DO UPDATE SET npc_id = EXCLUDED.npc_id, created_at = EXCLUDED.created_at
`

type InsertSharedBountyParams struct {
	WorldID   string `json:"world_id"`
	RoomID    string `json:"room_id"`
	NpcID     string `json:"npc_id"`
	CreatedAt int32  `json:"created_at"`
}

// ===================== Bounties =====================
func (q *Queries) InsertSharedBounty(ctx context.Context, arg InsertSharedBountyParams) error {
	_, err := q.db.Exec(ctx, insertSharedBounty,
		arg.WorldID,
		arg.RoomID,
		arg.NpcID,
		arg.CreatedAt,
	)
	return err
}

const insertSharedBuild = `-- name: InsertSharedBuild :exec

INSERT INTO shared_builds (world_id, room_id, build_id, placed_by)
VALUES ($1, $2, $3, $4)
`

type InsertSharedBuildParams struct {
	WorldID  string      `json:"world_id"`
	RoomID   string      `json:"room_id"`
	BuildID  string      `json:"build_id"`
	PlacedBy pgtype.UUID `json:"placed_by"`
}

// ===================== Building / Base =====================
func (q *Queries) InsertSharedBuild(ctx context.Context, arg InsertSharedBuildParams) error {
	_, err := q.db.Exec(ctx, insertSharedBuild,
		arg.WorldID,
		arg.RoomID,
		arg.BuildID,
		arg.PlacedBy,
	)
	return err
}

const insertSharedChest = `-- name: InsertSharedChest :exec

INSERT INTO shared_chests (world_id, room_id, item_id, item_name, stored_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertSharedChestParams struct {
	WorldID  string      `json:"world_id"`
	RoomID   string      `json:"room_id"`
	ItemID   string      `json:"item_id"`
	ItemName string      `json:"item_name"`
	StoredBy pgtype.UUID `json:"stored_by"`
}

// ===================== Chests =====================
func (q *Queries) InsertSharedChest(ctx context.Context, arg InsertSharedChestParams) error {
	_, err := q.db.Exec(ctx, insertSharedChest,
		arg.WorldID,
		arg.RoomID,
		arg.ItemID,
		arg.ItemName,
		arg.StoredBy,
	)
	return err
}

const insertSharedDeathPile = `-- name: InsertSharedDeathPile :exec

INSERT INTO shared_death_pile (world_id, room_id, item_id, item_name, item_desc)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSharedDeathPileParams struct {
	WorldID  string `json:"world_id"`
	RoomID   string `json:"room_id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

// ===================== Death Pile =====================
func (q *Queries) InsertSharedDeathPile(ctx context.Context, arg InsertSharedDeathPileParams) error {
	_, err := q.db.Exec(ctx, insertSharedDeathPile,
		arg.WorldID,
		arg.RoomID,
		arg.ItemID,
		arg.ItemName,
		arg.ItemDesc,
	)
	return err
}

const insertSharedHideoutUpgrade = `-- name: InsertSharedHideoutUpgrade :exec

INSERT INTO shared_hideout_upgrades (account_id, world_id, upgrade_id, installed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, world_id, upgrade_id) DO NOTHING
`

type InsertSharedHideoutUpgradeParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
	UpgradeID   string      `json:"upgrade_id"`
	InstalledAt int32       `json:"installed_at"`
}

// ===================== Hideout Upgrades =====================
func (q *Queries) InsertSharedHideoutUpgrade(ctx context.Context, arg InsertSharedHideoutUpgradeParams) error {
	_, err := q.db.Exec(ctx, insertSharedHideoutUpgrade,
		arg.AccountID,
		arg.WorldID,
		arg.UpgradeID,
		arg.InstalledAt,
	)
	return err
}

const insertSharedWorldEvent = `-- name: InsertSharedWorldEvent :exec

INSERT INTO shared_world_events
 (id, world_id, type, title, description, target_room, faction,
  payout_credits, payout_item_id, payout_item_name, payout_item_desc,
  status, expires_actions, created_actions, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertSharedWorldEventParams struct {
	ID             string      `json:"id"`
	WorldID        string      `json:"world_id"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	TargetRoom     string      `json:"target_room"`
	Faction        pgtype.Text `json:"faction"`
	PayoutCredits  int32       `json:"payout_credits"`
	PayoutItemID   pgtype.Text `json:"payout_item_id"`
	PayoutItemName pgtype.Text `json:"payout_item_name"`
	PayoutItemDesc pgtype.Text `json:"payout_item_desc"`
	Status         string      `json:"status"`
	ExpiresActions int32       `json:"expires_actions"`
	CreatedActions int32       `json:"created_actions"`
	CreatedAt      int32       `json:"created_at"`
}

// ===================== World Events =====================
func (q *Queries) InsertSharedWorldEvent(ctx context.Context, arg InsertSharedWorldEventParams) error {
	_, err := q.db.Exec(ctx, insertSharedWorldEvent,
		arg.ID,
		arg.WorldID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.TargetRoom,
		arg.Faction,
		arg.PayoutCredits,
		arg.PayoutItemID,
		arg.PayoutItemName,
		arg.PayoutItemDesc,
		arg.Status,
		arg.ExpiresActions,
		arg.CreatedActions,
		arg.CreatedAt,
	)
	return err
}

const isSharedRecipeUnlocked = `-- name: IsSharedRecipeUnlocked :one
SELECT COUNT(*) FROM shared_unlocked_recipes
WHERE account_id = $1 AND world_id = $2 AND recipe_id = $3
`

type IsSharedRecipeUnlockedParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	RecipeID  string      `json:"recipe_id"`
}

func (q *Queries) IsSharedRecipeUnlocked(ctx context.Context, arg IsSharedRecipeUnlockedParams) (int64, error) {
	row := q.db.QueryRow(ctx, isSharedRecipeUnlocked, arg.AccountID, arg.WorldID, arg.RecipeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isSharedRecruited = `-- name: IsSharedRecruited :one
SELECT npc_id FROM shared_faction_members
WHERE npc_id = $1
`

func (q *Queries) IsSharedRecruited(ctx context.Context, npcID string) (string, error) {
	row := q.db.QueryRow(ctx, isSharedRecruited, npcID)
	var npc_id string
	err := row.Scan(&npc_id)
	return npc_id, err
}

const isSharedRoomItemTaken = `-- name: IsSharedRoomItemTaken :one
SELECT item_id FROM shared_taken_room_items
WHERE world_id = $1 AND room_id = $2 AND item_id = $3
`

type IsSharedRoomItemTakenParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
	ItemID  string `json:"item_id"`
}

func (q *Queries) IsSharedRoomItemTaken(ctx context.Context, arg IsSharedRoomItemTakenParams) (string, error) {
	row := q.db.QueryRow(ctx, isSharedRoomItemTaken, arg.WorldID, arg.RoomID, arg.ItemID)
	var item_id string
	err := row.Scan(&item_id)
	return item_id, err
}

const listSharedActiveEvents = `-- name: ListSharedActiveEvents :many
SELECT id, type, title, description, target_room, faction,
       payout_credits, payout_item_id, payout_item_name, payout_item_desc,
       status, expires_actions, created_actions, created_at
FROM shared_world_events WHERE world_id = $1 AND status = 'active'
`

type ListSharedActiveEventsRow struct {
	ID             string      `json:"id"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	TargetRoom     string      `json:"target_room"`
	Faction        pgtype.Text `json:"faction"`
	PayoutCredits  int32       `json:"payout_credits"`
	PayoutItemID   pgtype.Text `json:"payout_item_id"`
	PayoutItemName pgtype.Text `json:"payout_item_name"`
	PayoutItemDesc pgtype.Text `json:"payout_item_desc"`
	Status         string      `json:"status"`
	ExpiresActions int32       `json:"expires_actions"`
	CreatedActions int32       `json:"created_actions"`
	CreatedAt      int32       `json:"created_at"`
}

func (q *Queries) ListSharedActiveEvents(ctx context.Context, worldID string) ([]ListSharedActiveEventsRow, error) {
	rows, err := q.db.Query(ctx, listSharedActiveEvents, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedActiveEventsRow{}
	for rows.Next() {
		var i ListSharedActiveEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.TargetRoom,
			&i.Faction,
			&i.PayoutCredits,
			&i.PayoutItemID,
			&i.PayoutItemName,
			&i.PayoutItemDesc,
			&i.Status,
			&i.ExpiresActions,
			&i.CreatedActions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedActiveQuestIDs = `-- name: ListSharedActiveQuestIDs :many
SELECT id FROM shared_quests
WHERE account_id = $1 AND world_id = $2 AND status = 'active'
`

type ListSharedActiveQuestIDsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) ListSharedActiveQuestIDs(ctx context.Context, arg ListSharedActiveQuestIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedActiveQuestIDs, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedActiveQuestsByTypeTarget = `-- name: ListSharedActiveQuestsByTypeTarget :many
SELECT id, title, description, status, obj_type, obj_target, obj_room,
       obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
       reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
       next_quest_id
FROM shared_quests
WHERE account_id = $1 AND world_id = $2 AND status = 'active' AND obj_type = $3 AND obj_target = $4
`

type ListSharedActiveQuestsByTypeTargetParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ObjType   string      `json:"obj_type"`
	ObjTarget string      `json:"obj_target"`
}

type ListSharedActiveQuestsByTypeTargetRow struct {
	ID             string      `json:"id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	ObjType        string      `json:"obj_type"`
	ObjTarget      string      `json:"obj_target"`
	ObjRoom        pgtype.Text `json:"obj_room"`
	ObjCount       int32       `json:"obj_count"`
	ObjProgress    int32       `json:"obj_progress"`
	RewardCredits  int32       `json:"reward_credits"`
	RewardXpSkill  pgtype.Text `json:"reward_xp_skill"`
	RewardXpAmount int32       `json:"reward_xp_amount"`
	RewardItemID   pgtype.Text `json:"reward_item_id"`
	RewardItemName pgtype.Text `json:"reward_item_name"`
	RewardItemDesc pgtype.Text `json:"reward_item_desc"`
	GiverNpcID     pgtype.Text `json:"giver_npc_id"`
	AcceptedAt     int32       `json:"accepted_at"`
	NextQuestID    string      `json:"next_quest_id"`
}

func (q *Queries) ListSharedActiveQuestsByTypeTarget(ctx context.Context, arg ListSharedActiveQuestsByTypeTargetParams) ([]ListSharedActiveQuestsByTypeTargetRow, error) {
	rows, err := q.db.Query(ctx, listSharedActiveQuestsByTypeTarget,
		arg.AccountID,
		arg.WorldID,
		arg.ObjType,
		arg.ObjTarget,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedActiveQuestsByTypeTargetRow{}
	for rows.Next() {
		var i ListSharedActiveQuestsByTypeTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ObjType,
			&i.ObjTarget,
			&i.ObjRoom,
			&i.ObjCount,
			&i.ObjProgress,
			&i.RewardCredits,
			&i.RewardXpSkill,
			&i.RewardXpAmount,
			&i.RewardItemID,
			&i.RewardItemName,
			&i.RewardItemDesc,
			&i.GiverNpcID,
			&i.AcceptedAt,
			&i.NextQuestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedAugments = `-- name: ListSharedAugments :many
SELECT skill, bonus, installed_at
FROM shared_player_augments
WHERE account_id = $1 AND world_id = $2
`

type ListSharedAugmentsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type ListSharedAugmentsRow struct {
	Skill       string `json:"skill"`
	Bonus       int32  `json:"bonus"`
	InstalledAt int32  `json:"installed_at"`
}

func (q *Queries) ListSharedAugments(ctx context.Context, arg ListSharedAugmentsParams) ([]ListSharedAugmentsRow, error) {
	rows, err := q.db.Query(ctx, listSharedAugments, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedAugmentsRow{}
	for rows.Next() {
		var i ListSharedAugmentsRow
		if err := rows.Scan(&i.Skill, &i.Bonus, &i.InstalledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedBuilds = `-- name: ListSharedBuilds :many
SELECT build_id FROM shared_builds
WHERE world_id = $1 AND room_id = $2
ORDER BY placed_at
`

type ListSharedBuildsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) ListSharedBuilds(ctx context.Context, arg ListSharedBuildsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedBuilds, arg.WorldID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var build_id string
		if err := rows.Scan(&build_id); err != nil {
			return nil, err
		}
		items = append(items, build_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedEnchants = `-- name: ListSharedEnchants :many
SELECT item_id, enchant_id, level
FROM shared_enchants
WHERE account_id = $1 AND world_id = $2 AND item_id = $3
`

type ListSharedEnchantsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
}

type ListSharedEnchantsRow struct {
	ItemID    string `json:"item_id"`
	EnchantID string `json:"enchant_id"`
	Level     int32  `json:"level"`
}

func (q *Queries) ListSharedEnchants(ctx context.Context, arg ListSharedEnchantsParams) ([]ListSharedEnchantsRow, error) {
	rows, err := q.db.Query(ctx, listSharedEnchants, arg.AccountID, arg.WorldID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedEnchantsRow{}
	for rows.Next() {
		var i ListSharedEnchantsRow
		if err := rows.Scan(&i.ItemID, &i.EnchantID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedExpiredBaseRaids = `-- name: ListSharedExpiredBaseRaids :many
SELECT id FROM shared_world_events
WHERE world_id = $1 AND type = 'base-raid' AND target_room = $2 AND status = 'active'
AND (created_actions + expires_actions) <= $3
`

type ListSharedExpiredBaseRaidsParams struct {
	WorldID        string `json:"world_id"`
	TargetRoom     string `json:"target_room"`
	CreatedActions int32  `json:"created_actions"`
}

func (q *Queries) ListSharedExpiredBaseRaids(ctx context.Context, arg ListSharedExpiredBaseRaidsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedExpiredBaseRaids, arg.WorldID, arg.TargetRoom, arg.CreatedActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedHideoutUpgrades = `-- name: ListSharedHideoutUpgrades :many
SELECT upgrade_id, installed_at
FROM shared_hideout_upgrades
WHERE account_id = $1 AND world_id = $2
`

type ListSharedHideoutUpgradesParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type ListSharedHideoutUpgradesRow struct {
	UpgradeID   string `json:"upgrade_id"`
	InstalledAt int32  `json:"installed_at"`
}

func (q *Queries) ListSharedHideoutUpgrades(ctx context.Context, arg ListSharedHideoutUpgradesParams) ([]ListSharedHideoutUpgradesRow, error) {
	rows, err := q.db.Query(ctx, listSharedHideoutUpgrades, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedHideoutUpgradesRow{}
	for rows.Next() {
		var i ListSharedHideoutUpgradesRow
		if err := rows.Scan(&i.UpgradeID, &i.InstalledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedHighRepFactions = `-- name: ListSharedHighRepFactions :many
SELECT faction, value FROM shared_player_reputation
WHERE account_id = $1 AND world_id = $2 AND value >= 3
`

type ListSharedHighRepFactionsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type ListSharedHighRepFactionsRow struct {
	Faction string `json:"faction"`
	Value   int32  `json:"value"`
}

func (q *Queries) ListSharedHighRepFactions(ctx context.Context, arg ListSharedHighRepFactionsParams) ([]ListSharedHighRepFactionsRow, error) {
	rows, err := q.db.Query(ctx, listSharedHighRepFactions, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedHighRepFactionsRow{}
	for rows.Next() {
		var i ListSharedHighRepFactionsRow
		if err := rows.Scan(&i.Faction, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedInventory = `-- name: ListSharedInventory :many

SELECT item_id, item_name, item_desc
FROM shared_inventory
WHERE account_id = $1 AND world_id = $2
`

type ListSharedInventoryParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type ListSharedInventoryRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

// ===================== Inventory =====================
func (q *Queries) ListSharedInventory(ctx context.Context, arg ListSharedInventoryParams) ([]ListSharedInventoryRow, error) {
	rows, err := q.db.Query(ctx, listSharedInventory, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedInventoryRow{}
	for rows.Next() {
		var i ListSharedInventoryRow
		if err := rows.Scan(&i.ItemID, &i.ItemName, &i.ItemDesc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedRandomChestItems = `-- name: ListSharedRandomChestItems :many
SELECT item_id, item_name FROM shared_chests
WHERE world_id = $1 AND room_id = $2
ORDER BY RANDOM() LIMIT $3
`

type ListSharedRandomChestItemsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
	Limit   int32  `json:"limit"`
}

type ListSharedRandomChestItemsRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
}

func (q *Queries) ListSharedRandomChestItems(ctx context.Context, arg ListSharedRandomChestItemsParams) ([]ListSharedRandomChestItemsRow, error) {
	rows, err := q.db.Query(ctx, listSharedRandomChestItems, arg.WorldID, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedRandomChestItemsRow{}
	for rows.Next() {
		var i ListSharedRandomChestItemsRow
		if err := rows.Scan(&i.ItemID, &i.ItemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedReputations = `-- name: ListSharedReputations :many
SELECT faction, value FROM shared_player_reputation
WHERE account_id = $1 AND world_id = $2
`

type ListSharedReputationsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type ListSharedReputationsRow struct {
	Faction string `json:"faction"`
	Value   int32  `json:"value"`
}

func (q *Queries) ListSharedReputations(ctx context.Context, arg ListSharedReputationsParams) ([]ListSharedReputationsRow, error) {
	rows, err := q.db.Query(ctx, listSharedReputations, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedReputationsRow{}
	for rows.Next() {
		var i ListSharedReputationsRow
		if err := rows.Scan(&i.Faction, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedSkills = `-- name: ListSharedSkills :many
SELECT skill, level, xp
FROM shared_player_skills
WHERE account_id = $1 AND world_id = $2
`

type ListSharedSkillsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

type ListSharedSkillsRow struct {
	Skill string `json:"skill"`
	Level int32  `json:"level"`
	Xp    int32  `json:"xp"`
}

func (q *Queries) ListSharedSkills(ctx context.Context, arg ListSharedSkillsParams) ([]ListSharedSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSharedSkills, arg.AccountID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedSkillsRow{}
	for rows.Next() {
		var i ListSharedSkillsRow
		if err := rows.Scan(&i.Skill, &i.Level, &i.Xp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedTakenRoomItems = `-- name: ListSharedTakenRoomItems :many
SELECT item_id FROM shared_taken_room_items
WHERE world_id = $1 AND room_id = $2
`

type ListSharedTakenRoomItemsParams struct {
	WorldID string `json:"world_id"`
	RoomID  string `json:"room_id"`
}

func (q *Queries) ListSharedTakenRoomItems(ctx context.Context, arg ListSharedTakenRoomItemsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedTakenRoomItems, arg.WorldID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSharedShardCollected = `-- name: MarkSharedShardCollected :exec
UPDATE shared_crystal_shards SET collected = TRUE, collected_at = $1
WHERE world_id = $2 AND shard_id = $3
`

type MarkSharedShardCollectedParams struct {
	CollectedAt int32  `json:"collected_at"`
	WorldID     string `json:"world_id"`
	ShardID     string `json:"shard_id"`
}

func (q *Queries) MarkSharedShardCollected(ctx context.Context, arg MarkSharedShardCollectedParams) error {
	_, err := q.db.Exec(ctx, markSharedShardCollected, arg.CollectedAt, arg.WorldID, arg.ShardID)
	return err
}

const markSharedSystemHacked = `-- name: MarkSharedSystemHacked :exec
INSERT INTO shared_system_state (world_id, system_id, hacked, intrusion_level, alert_level)
VALUES ($1, $2, TRUE, 0, 0)
ON CONFLICT (world_id, system_id)
DO UPDATE SET hacked = TRUE
`

type MarkSharedSystemHackedParams struct {
	WorldID  string `json:"world_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) MarkSharedSystemHacked(ctx context.Context, arg MarkSharedSystemHackedParams) error {
	_, err := q.db.Exec(ctx, markSharedSystemHacked, arg.WorldID, arg.SystemID)
	return err
}

const markSharedVisited = `-- name: MarkSharedVisited :exec

INSERT INTO shared_visited (account_id, world_id, room_id)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, world_id, room_id) DO NOTHING
`

type MarkSharedVisitedParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	RoomID    string      `json:"room_id"`
}

// ===================== Visited =====================
func (q *Queries) MarkSharedVisited(ctx context.Context, arg MarkSharedVisitedParams) error {
	_, err := q.db.Exec(ctx, markSharedVisited, arg.AccountID, arg.WorldID, arg.RoomID)
	return err
}

const plantSharedCrop = `-- name: PlantSharedCrop :exec
INSERT INTO shared_crops (world_id, room_id, slot, seed_id, planted_at_action, ready_at_action)
VALUES ($1, $2, $3, $4, $5, $6)
`

type PlantSharedCropParams struct {
	WorldID         string `json:"world_id"`
	RoomID          string `json:"room_id"`
	Slot            int32  `json:"slot"`
	SeedID          string `json:"seed_id"`
	PlantedAtAction int32  `json:"planted_at_action"`
	ReadyAtAction   int32  `json:"ready_at_action"`
}

func (q *Queries) PlantSharedCrop(ctx context.Context, arg PlantSharedCropParams) error {
	_, err := q.db.Exec(ctx, plantSharedCrop,
		arg.WorldID,
		arg.RoomID,
		arg.Slot,
		arg.SeedID,
		arg.PlantedAtAction,
		arg.ReadyAtAction,
	)
	return err
}

const progressSharedQuest = `-- name: ProgressSharedQuest :exec
UPDATE shared_quests
SET obj_progress = obj_progress + $1
WHERE id = $2 AND account_id = $3 AND world_id = $4 AND status = 'active'
`

type ProgressSharedQuestParams struct {
	ObjProgress int32       `json:"obj_progress"`
	ID          string      `json:"id"`
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
}

func (q *Queries) ProgressSharedQuest(ctx context.Context, arg ProgressSharedQuestParams) error {
	_, err := q.db.Exec(ctx, progressSharedQuest,
		arg.ObjProgress,
		arg.ID,
		arg.AccountID,
		arg.WorldID,
	)
	return err
}

const quitSharedArena = `-- name: QuitSharedArena :exec
DELETE FROM shared_arena_sessions
WHERE account_id = $1 AND world_id = $2
`

type QuitSharedArenaParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) QuitSharedArena(ctx context.Context, arg QuitSharedArenaParams) error {
	_, err := q.db.Exec(ctx, quitSharedArena, arg.AccountID, arg.WorldID)
	return err
}

const recruitSharedMember = `-- name: RecruitSharedMember :exec
INSERT INTO shared_faction_members (account_id, world_id, npc_id, npc_name, npc_desc, role, stationed_room, loyalty, recruited_at)
VALUES ($1, $2, $3, $4, $5, $6, '', 50, $7)
`

type RecruitSharedMemberParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
	NpcID       string      `json:"npc_id"`
	NpcName     string      `json:"npc_name"`
	NpcDesc     pgtype.Text `json:"npc_desc"`
	Role        string      `json:"role"`
	RecruitedAt int32       `json:"recruited_at"`
}

func (q *Queries) RecruitSharedMember(ctx context.Context, arg RecruitSharedMemberParams) error {
	_, err := q.db.Exec(ctx, recruitSharedMember,
		arg.AccountID,
		arg.WorldID,
		arg.NpcID,
		arg.NpcName,
		arg.NpcDesc,
		arg.Role,
		arg.RecruitedAt,
	)
	return err
}

const removeOneSharedItem = `-- name: RemoveOneSharedItem :exec
DELETE FROM shared_inventory
WHERE id = (
  SELECT si.id FROM shared_inventory si
  WHERE si.account_id = $1 AND si.world_id = $2 AND si.item_id = $3
  LIMIT 1
)
`

type RemoveOneSharedItemParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
}

func (q *Queries) RemoveOneSharedItem(ctx context.Context, arg RemoveOneSharedItemParams) error {
	_, err := q.db.Exec(ctx, removeOneSharedItem, arg.AccountID, arg.WorldID, arg.ItemID)
	return err
}

const removeSharedItem = `-- name: RemoveSharedItem :execresult
DELETE FROM shared_inventory
WHERE account_id = $1 AND world_id = $2 AND item_id = $3
`

type RemoveSharedItemParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
}

func (q *Queries) RemoveSharedItem(ctx context.Context, arg RemoveSharedItemParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeSharedItem, arg.AccountID, arg.WorldID, arg.ItemID)
}

const resolveSharedWorldEvent = `-- name: ResolveSharedWorldEvent :exec
UPDATE shared_world_events SET status = 'resolved'
WHERE id = $1
`

func (q *Queries) ResolveSharedWorldEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resolveSharedWorldEvent, id)
	return err
}

const respawnExpiredNPCs = `-- name: RespawnExpiredNPCs :exec
UPDATE shared_npc_state
SET alive = TRUE, respawn_at = NULL
WHERE world_id = $1 AND alive = FALSE AND respawn_at IS NOT NULL AND respawn_at <= now()
`

func (q *Queries) RespawnExpiredNPCs(ctx context.Context, worldID string) error {
	_, err := q.db.Exec(ctx, respawnExpiredNPCs, worldID)
	return err
}

const respawnExpiredResources = `-- name: RespawnExpiredResources :exec
UPDATE shared_resources
SET depleted = FALSE, respawn_at = NULL
WHERE world_id = $1 AND depleted = TRUE AND respawn_at IS NOT NULL AND respawn_at <= now()
`

func (q *Queries) RespawnExpiredResources(ctx context.Context, worldID string) error {
	_, err := q.db.Exec(ctx, respawnExpiredResources, worldID)
	return err
}

const saveSharedArena = `-- name: SaveSharedArena :exec
UPDATE shared_arena_sessions
SET wave = $1, enemies = $2
WHERE id = $3
`

type SaveSharedArenaParams struct {
	Wave    int32       `json:"wave"`
	Enemies string      `json:"enemies"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) SaveSharedArena(ctx context.Context, arg SaveSharedArenaParams) error {
	_, err := q.db.Exec(ctx, saveSharedArena, arg.Wave, arg.Enemies, arg.ID)
	return err
}

const seedSharedCrystalShard = `-- name: SeedSharedCrystalShard :exec

INSERT INTO shared_crystal_shards (world_id, shard_id, biome, collected, collected_at)
VALUES ($1, $2, $3, FALSE, 0)
ON CONFLICT (world_id, shard_id) DO NOTHING
`

type SeedSharedCrystalShardParams struct {
	WorldID string `json:"world_id"`
	ShardID string `json:"shard_id"`
	Biome   string `json:"biome"`
}

// ===================== Crystal Shards =====================
func (q *Queries) SeedSharedCrystalShard(ctx context.Context, arg SeedSharedCrystalShardParams) error {
	_, err := q.db.Exec(ctx, seedSharedCrystalShard, arg.WorldID, arg.ShardID, arg.Biome)
	return err
}

const setSharedHideout = `-- name: SetSharedHideout :exec
UPDATE shared_player_faction SET hideout_room_id = $1
WHERE account_id = $2 AND world_id = $3
`

type SetSharedHideoutParams struct {
	HideoutRoomID pgtype.Text `json:"hideout_room_id"`
	AccountID     pgtype.UUID `json:"account_id"`
	WorldID       string      `json:"world_id"`
}

func (q *Queries) SetSharedHideout(ctx context.Context, arg SetSharedHideoutParams) error {
	_, err := q.db.Exec(ctx, setSharedHideout, arg.HideoutRoomID, arg.AccountID, arg.WorldID)
	return err
}

const setSharedLockUnlocked = `-- name: SetSharedLockUnlocked :exec
INSERT INTO shared_lock_state (world_id, lock_id, unlocked)
VALUES ($1, $2, TRUE)
ON CONFLICT (world_id, lock_id)
DO UPDATE SET unlocked = TRUE
`

type SetSharedLockUnlockedParams struct {
	WorldID string `json:"world_id"`
	LockID  string `json:"lock_id"`
}

func (q *Queries) SetSharedLockUnlocked(ctx context.Context, arg SetSharedLockUnlockedParams) error {
	_, err := q.db.Exec(ctx, setSharedLockUnlocked, arg.WorldID, arg.LockID)
	return err
}

const setSharedPlayerFlag = `-- name: SetSharedPlayerFlag :exec

INSERT INTO shared_player_flags (account_id, world_id, flag)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, world_id, flag) DO NOTHING
`

type SetSharedPlayerFlagParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Flag      string      `json:"flag"`
}

// ===================== Player Flags =====================
func (q *Queries) SetSharedPlayerFlag(ctx context.Context, arg SetSharedPlayerFlagParams) error {
	_, err := q.db.Exec(ctx, setSharedPlayerFlag, arg.AccountID, arg.WorldID, arg.Flag)
	return err
}

const setSharedVulnWindow = `-- name: SetSharedVulnWindow :exec

INSERT INTO shared_vuln_windows (world_id, system_id, bonus, expires_action)
VALUES ($1, $2, $3, $4)
ON CONFLICT (world_id, system_id)
DO UPDATE SET bonus = EXCLUDED.bonus, expires_action = EXCLUDED.expires_action
`

type SetSharedVulnWindowParams struct {
	WorldID       string `json:"world_id"`
	SystemID      string `json:"system_id"`
	Bonus         int32  `json:"bonus"`
	ExpiresAction int32  `json:"expires_action"`
}

// ===================== Vuln Windows =====================
func (q *Queries) SetSharedVulnWindow(ctx context.Context, arg SetSharedVulnWindowParams) error {
	_, err := q.db.Exec(ctx, setSharedVulnWindow,
		arg.WorldID,
		arg.SystemID,
		arg.Bonus,
		arg.ExpiresAction,
	)
	return err
}

const sharedFactionExists = `-- name: SharedFactionExists :one
SELECT account_id FROM shared_player_faction
WHERE account_id = $1 AND world_id = $2
`

type SharedFactionExistsParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) SharedFactionExists(ctx context.Context, arg SharedFactionExistsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sharedFactionExists, arg.AccountID, arg.WorldID)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const sharedMemberCount = `-- name: SharedMemberCount :one
SELECT COUNT(*) FROM shared_faction_members
WHERE account_id = $1 AND world_id = $2
`

type SharedMemberCountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
}

func (q *Queries) SharedMemberCount(ctx context.Context, arg SharedMemberCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, sharedMemberCount, arg.AccountID, arg.WorldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const startSharedArena = `-- name: StartSharedArena :exec

INSERT INTO shared_arena_sessions (account_id, world_id, game_type, wave, enemies)
VALUES ($1, $2, $3, $4, $5)
`

type StartSharedArenaParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	GameType  string      `json:"game_type"`
	Wave      int32       `json:"wave"`
	Enemies   string      `json:"enemies"`
}

// ===================== Arena =====================
func (q *Queries) StartSharedArena(ctx context.Context, arg StartSharedArenaParams) error {
	_, err := q.db.Exec(ctx, startSharedArena,
		arg.AccountID,
		arg.WorldID,
		arg.GameType,
		arg.Wave,
		arg.Enemies,
	)
	return err
}

const takeSharedRoomItem = `-- name: TakeSharedRoomItem :exec

INSERT INTO shared_taken_room_items (world_id, room_id, item_id, taken_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (world_id, room_id, item_id) DO NOTHING
`

type TakeSharedRoomItemParams struct {
	WorldID string      `json:"world_id"`
	RoomID  string      `json:"room_id"`
	ItemID  string      `json:"item_id"`
	TakenBy pgtype.UUID `json:"taken_by"`
}

// ===================== Taken Room Items =====================
func (q *Queries) TakeSharedRoomItem(ctx context.Context, arg TakeSharedRoomItemParams) error {
	_, err := q.db.Exec(ctx, takeSharedRoomItem,
		arg.WorldID,
		arg.RoomID,
		arg.ItemID,
		arg.TakenBy,
	)
	return err
}

const undepleteSharedResource = `-- name: UndepleteSharedResource :exec
UPDATE shared_resources
SET depleted = FALSE, respawn_at = NULL
WHERE world_id = $1 AND resource_id = $2
`

type UndepleteSharedResourceParams struct {
	WorldID    string `json:"world_id"`
	ResourceID string `json:"resource_id"`
}

func (q *Queries) UndepleteSharedResource(ctx context.Context, arg UndepleteSharedResourceParams) error {
	_, err := q.db.Exec(ctx, undepleteSharedResource, arg.WorldID, arg.ResourceID)
	return err
}

const unlockSharedRecipe = `-- name: UnlockSharedRecipe :exec

INSERT INTO shared_unlocked_recipes (account_id, world_id, recipe_id, unlocked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, world_id, recipe_id) DO NOTHING
`

type UnlockSharedRecipeParams struct {
	AccountID  pgtype.UUID `json:"account_id"`
	WorldID    string      `json:"world_id"`
	RecipeID   string      `json:"recipe_id"`
	UnlockedAt int32       `json:"unlocked_at"`
}

// ===================== Recipes =====================
func (q *Queries) UnlockSharedRecipe(ctx context.Context, arg UnlockSharedRecipeParams) error {
	_, err := q.db.Exec(ctx, unlockSharedRecipe,
		arg.AccountID,
		arg.WorldID,
		arg.RecipeID,
		arg.UnlockedAt,
	)
	return err
}

const updateSharedFactionMemberStation = `-- name: UpdateSharedFactionMemberStation :exec
UPDATE shared_faction_members SET stationed_room = $1
WHERE npc_id = $2
`

type UpdateSharedFactionMemberStationParams struct {
	StationedRoom pgtype.Text `json:"stationed_room"`
	NpcID         string      `json:"npc_id"`
}

func (q *Queries) UpdateSharedFactionMemberStation(ctx context.Context, arg UpdateSharedFactionMemberStationParams) error {
	_, err := q.db.Exec(ctx, updateSharedFactionMemberStation, arg.StationedRoom, arg.NpcID)
	return err
}

const upsertSharedAugment = `-- name: UpsertSharedAugment :exec

INSERT INTO shared_player_augments (account_id, world_id, skill, bonus, installed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, world_id, skill)
DO UPDATE SET bonus = EXCLUDED.bonus, installed_at = EXCLUDED.installed_at
`

type UpsertSharedAugmentParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	WorldID     string      `json:"world_id"`
	Skill       string      `json:"skill"`
	Bonus       int32       `json:"bonus"`
	InstalledAt int32       `json:"installed_at"`
}

// ===================== Augments =====================
func (q *Queries) UpsertSharedAugment(ctx context.Context, arg UpsertSharedAugmentParams) error {
	_, err := q.db.Exec(ctx, upsertSharedAugment,
		arg.AccountID,
		arg.WorldID,
		arg.Skill,
		arg.Bonus,
		arg.InstalledAt,
	)
	return err
}

const upsertSharedEquippedArmor = `-- name: UpsertSharedEquippedArmor :exec
INSERT INTO shared_equipped_armor (account_id, world_id, item_id, item_name, defense)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, world_id)
DO UPDATE SET item_id = EXCLUDED.item_id, item_name = EXCLUDED.item_name, defense = EXCLUDED.defense
`

type UpsertSharedEquippedArmorParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	ItemID    string      `json:"item_id"`
	ItemName  string      `json:"item_name"`
	Defense   int32       `json:"defense"`
}

func (q *Queries) UpsertSharedEquippedArmor(ctx context.Context, arg UpsertSharedEquippedArmorParams) error {
	_, err := q.db.Exec(ctx, upsertSharedEquippedArmor,
		arg.AccountID,
		arg.WorldID,
		arg.ItemID,
		arg.ItemName,
		arg.Defense,
	)
	return err
}

const upsertSharedGeneratedContent = `-- name: UpsertSharedGeneratedContent :exec
INSERT INTO shared_generated_content (world_id, prompt_hash, type, yaml_blob, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (world_id, prompt_hash)
DO UPDATE SET type = EXCLUDED.type, yaml_blob = EXCLUDED.yaml_blob, created_at = EXCLUDED.created_at
`

type UpsertSharedGeneratedContentParams struct {
	WorldID    string `json:"world_id"`
	PromptHash string `json:"prompt_hash"`
	Type       string `json:"type"`
	YamlBlob   string `json:"yaml_blob"`
	CreatedAt  int32  `json:"created_at"`
}

func (q *Queries) UpsertSharedGeneratedContent(ctx context.Context, arg UpsertSharedGeneratedContentParams) error {
	_, err := q.db.Exec(ctx, upsertSharedGeneratedContent,
		arg.WorldID,
		arg.PromptHash,
		arg.Type,
		arg.YamlBlob,
		arg.CreatedAt,
	)
	return err
}

const upsertSharedItemMod = `-- name: UpsertSharedItemMod :exec

INSERT INTO shared_item_mods (account_id, world_id, item_instance, mod_id, applied_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, world_id, item_instance)
DO UPDATE SET mod_id = EXCLUDED.mod_id, applied_at = EXCLUDED.applied_at
`

type UpsertSharedItemModParams struct {
	AccountID    pgtype.UUID `json:"account_id"`
	WorldID      string      `json:"world_id"`
	ItemInstance string      `json:"item_instance"`
	ModID        string      `json:"mod_id"`
	AppliedAt    int32       `json:"applied_at"`
}

// ===================== Item Mods =====================
func (q *Queries) UpsertSharedItemMod(ctx context.Context, arg UpsertSharedItemModParams) error {
	_, err := q.db.Exec(ctx, upsertSharedItemMod,
		arg.AccountID,
		arg.WorldID,
		arg.ItemInstance,
		arg.ModID,
		arg.AppliedAt,
	)
	return err
}

const upsertSharedNPCAlive = `-- name: UpsertSharedNPCAlive :exec
INSERT INTO shared_npc_state (world_id, npc_id, room_id, hp, alive, respawn_at)
VALUES ($1, $2, $3, $4, TRUE, NULL)
ON CONFLICT (world_id, npc_id)
DO UPDATE SET hp = EXCLUDED.hp, alive = TRUE, respawn_at = NULL
`

type UpsertSharedNPCAliveParams struct {
	WorldID string `json:"world_id"`
	NpcID   string `json:"npc_id"`
	RoomID  string `json:"room_id"`
	Hp      int32  `json:"hp"`
}

func (q *Queries) UpsertSharedNPCAlive(ctx context.Context, arg UpsertSharedNPCAliveParams) error {
	_, err := q.db.Exec(ctx, upsertSharedNPCAlive,
		arg.WorldID,
		arg.NpcID,
		arg.RoomID,
		arg.Hp,
	)
	return err
}

const upsertSharedNPCDead = `-- name: UpsertSharedNPCDead :exec
INSERT INTO shared_npc_state (world_id, npc_id, room_id, hp, alive, respawn_at)
VALUES ($1, $2, $3, $4, FALSE, $5)
ON CONFLICT (world_id, npc_id)
DO UPDATE SET hp = EXCLUDED.hp, alive = FALSE, respawn_at = EXCLUDED.respawn_at
`

type UpsertSharedNPCDeadParams struct {
	WorldID   string             `json:"world_id"`
	NpcID     string             `json:"npc_id"`
	RoomID    string             `json:"room_id"`
	Hp        int32              `json:"hp"`
	RespawnAt pgtype.Timestamptz `json:"respawn_at"`
}

func (q *Queries) UpsertSharedNPCDead(ctx context.Context, arg UpsertSharedNPCDeadParams) error {
	_, err := q.db.Exec(ctx, upsertSharedNPCDead,
		arg.WorldID,
		arg.NpcID,
		arg.RoomID,
		arg.Hp,
		arg.RespawnAt,
	)
	return err
}

const upsertSharedNPCMemory = `-- name: UpsertSharedNPCMemory :exec

INSERT INTO shared_npc_memory (world_id, npc_id, action, ts)
VALUES ($1, $2, $3, $4)
ON CONFLICT (world_id, npc_id, action)
DO UPDATE SET ts = EXCLUDED.ts
`

type UpsertSharedNPCMemoryParams struct {
	WorldID string `json:"world_id"`
	NpcID   string `json:"npc_id"`
	Action  string `json:"action"`
	Ts      int32  `json:"ts"`
}

// ===================== NPC Memory =====================
func (q *Queries) UpsertSharedNPCMemory(ctx context.Context, arg UpsertSharedNPCMemoryParams) error {
	_, err := q.db.Exec(ctx, upsertSharedNPCMemory,
		arg.WorldID,
		arg.NpcID,
		arg.Action,
		arg.Ts,
	)
	return err
}

const upsertSharedPlayerState = `-- name: UpsertSharedPlayerState :exec
INSERT INTO shared_player_state (account_id, world_id, room_id, hp, max_hp, credits)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, world_id)
DO UPDATE SET room_id = EXCLUDED.room_id, hp = EXCLUDED.hp, max_hp = EXCLUDED.max_hp, credits = EXCLUDED.credits
`

type UpsertSharedPlayerStateParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	RoomID    string      `json:"room_id"`
	Hp        int32       `json:"hp"`
	MaxHp     int32       `json:"max_hp"`
	Credits   int32       `json:"credits"`
}

func (q *Queries) UpsertSharedPlayerState(ctx context.Context, arg UpsertSharedPlayerStateParams) error {
	_, err := q.db.Exec(ctx, upsertSharedPlayerState,
		arg.AccountID,
		arg.WorldID,
		arg.RoomID,
		arg.Hp,
		arg.MaxHp,
		arg.Credits,
	)
	return err
}

const upsertSharedReputation = `-- name: UpsertSharedReputation :exec
INSERT INTO shared_player_reputation (account_id, world_id, faction, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, world_id, faction)
DO UPDATE SET value = EXCLUDED.value
`

type UpsertSharedReputationParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Faction   string      `json:"faction"`
	Value     int32       `json:"value"`
}

func (q *Queries) UpsertSharedReputation(ctx context.Context, arg UpsertSharedReputationParams) error {
	_, err := q.db.Exec(ctx, upsertSharedReputation,
		arg.AccountID,
		arg.WorldID,
		arg.Faction,
		arg.Value,
	)
	return err
}

const upsertSharedSkill = `-- name: UpsertSharedSkill :exec
INSERT INTO shared_player_skills (account_id, world_id, skill, level, xp)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, world_id, skill)
DO UPDATE SET level = EXCLUDED.level, xp = EXCLUDED.xp
`

type UpsertSharedSkillParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Skill     string      `json:"skill"`
	Level     int32       `json:"level"`
	Xp        int32       `json:"xp"`
}

func (q *Queries) UpsertSharedSkill(ctx context.Context, arg UpsertSharedSkillParams) error {
	_, err := q.db.Exec(ctx, upsertSharedSkill,
		arg.AccountID,
		arg.WorldID,
		arg.Skill,
		arg.Level,
		arg.Xp,
	)
	return err
}

const upsertSharedStealth = `-- name: UpsertSharedStealth :exec

INSERT INTO shared_player_stealth (account_id, world_id, level, disguise)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, world_id)
DO UPDATE SET level = EXCLUDED.level, disguise = EXCLUDED.disguise
`

type UpsertSharedStealthParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorldID   string      `json:"world_id"`
	Level     int32       `json:"level"`
	Disguise  string      `json:"disguise"`
}

// ===================== Stealth =====================
func (q *Queries) UpsertSharedStealth(ctx context.Context, arg UpsertSharedStealthParams) error {
	_, err := q.db.Exec(ctx, upsertSharedStealth,
		arg.AccountID,
		arg.WorldID,
		arg.Level,
		arg.Disguise,
	)
	return err
}

const upsertSharedSystemAlert = `-- name: UpsertSharedSystemAlert :exec
INSERT INTO shared_system_state (world_id, system_id, hacked, intrusion_level, alert_level)
VALUES ($1, $2, FALSE, 0, $3)
ON CONFLICT (world_id, system_id)
DO UPDATE SET alert_level = EXCLUDED.alert_level
`

type UpsertSharedSystemAlertParams struct {
	WorldID    string `json:"world_id"`
	SystemID   string `json:"system_id"`
	AlertLevel int32  `json:"alert_level"`
}

func (q *Queries) UpsertSharedSystemAlert(ctx context.Context, arg UpsertSharedSystemAlertParams) error {
	_, err := q.db.Exec(ctx, upsertSharedSystemAlert, arg.WorldID, arg.SystemID, arg.AlertLevel)
	return err
}

const upsertSharedWeather = `-- name: UpsertSharedWeather :exec
INSERT INTO shared_weather_state (world_id, biome, condition, expires_action)
VALUES ($1, $2, $3, $4)
ON CONFLICT (world_id, biome)
DO UPDATE SET condition = EXCLUDED.condition, expires_action = EXCLUDED.expires_action
`

type UpsertSharedWeatherParams struct {
	WorldID       string `json:"world_id"`
	Biome         string `json:"biome"`
	Condition     string `json:"condition"`
	ExpiresAction int32  `json:"expires_action"`
}

func (q *Queries) UpsertSharedWeather(ctx context.Context, arg UpsertSharedWeatherParams) error {
	_, err := q.db.Exec(ctx, upsertSharedWeather,
		arg.WorldID,
		arg.Biome,
		arg.Condition,
		arg.ExpiresAction,
	)
	return err
}
