// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: arena.sql

package sqliteq

import (
	"context"
)

const getActiveArenaSession = `-- name: GetActiveArenaSession :one
SELECT id, game_type, phase, wave, enemies_json, reward_credits,
       reward_item_id, reward_item_name, reward_item_desc, status, started_at
FROM arena_sessions WHERE status = 'active' LIMIT 1
`

func (q *Queries) GetActiveArenaSession(ctx context.Context) (ArenaSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveArenaSession)
	var i ArenaSession
	err := row.Scan(
		&i.ID,
		&i.GameType,
		&i.Phase,
		&i.Wave,
		&i.EnemiesJson,
		&i.RewardCredits,
		&i.RewardItemID,
		&i.RewardItemName,
		&i.RewardItemDesc,
		&i.Status,
		&i.StartedAt,
	)
	return i, err
}

const insertArenaSession = `-- name: InsertArenaSession :exec
INSERT OR REPLACE INTO arena_sessions
 (id, game_type, phase, wave, enemies_json, reward_credits,
  reward_item_id, reward_item_name, reward_item_desc, status, started_at)
 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertArenaSessionParams struct {
	ID             string `json:"id"`
	GameType       string `json:"game_type"`
	Phase          string `json:"phase"`
	Wave           int64  `json:"wave"`
	EnemiesJson    string `json:"enemies_json"`
	RewardCredits  int64  `json:"reward_credits"`
	RewardItemID   string `json:"reward_item_id"`
	RewardItemName string `json:"reward_item_name"`
	RewardItemDesc string `json:"reward_item_desc"`
	Status         string `json:"status"`
	StartedAt      int64  `json:"started_at"`
}

func (q *Queries) InsertArenaSession(ctx context.Context, arg InsertArenaSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertArenaSession,
		arg.ID,
		arg.GameType,
		arg.Phase,
		arg.Wave,
		arg.EnemiesJson,
		arg.RewardCredits,
		arg.RewardItemID,
		arg.RewardItemName,
		arg.RewardItemDesc,
		arg.Status,
		arg.StartedAt,
	)
	return err
}

const quitArenaSession = `-- name: QuitArenaSession :exec
UPDATE arena_sessions SET status = 'lost' WHERE status = 'active'
`

func (q *Queries) QuitArenaSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, quitArenaSession)
	return err
}

const updateArenaSession = `-- name: UpdateArenaSession :exec
UPDATE arena_sessions SET phase = ?, wave = ?, enemies_json = ?, status = ? WHERE id = ?
`

type UpdateArenaSessionParams struct {
	Phase       string `json:"phase"`
	Wave        int64  `json:"wave"`
	EnemiesJson string `json:"enemies_json"`
	Status      string `json:"status"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateArenaSession(ctx context.Context, arg UpdateArenaSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateArenaSession,
		arg.Phase,
		arg.Wave,
		arg.EnemiesJson,
		arg.Status,
		arg.ID,
	)
	return err
}
