// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: base.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const countActiveBaseRaids = `-- name: CountActiveBaseRaids :one
SELECT COUNT(*) FROM world_events WHERE type = 'base-raid' AND target_room = ? AND status = 'active'
`

func (q *Queries) CountActiveBaseRaids(ctx context.Context, targetRoom string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBaseRaids, targetRoom)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBuildsInRoom = `-- name: CountBuildsInRoom :one
SELECT COUNT(*) FROM builds WHERE room_id = ?
`

func (q *Queries) CountBuildsInRoom(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBuildsInRoom, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChestItemBase = `-- name: DeleteChestItemBase :exec
DELETE FROM chests WHERE room_id = ? AND item_id = ?
`

type DeleteChestItemBaseParams struct {
	RoomID string `json:"room_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteChestItemBase(ctx context.Context, arg DeleteChestItemBaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteChestItemBase, arg.RoomID, arg.ItemID)
	return err
}

const getActionCountBase = `-- name: GetActionCountBase :one
SELECT count FROM player_actions WHERE id = 1
`

func (q *Queries) GetActionCountBase(ctx context.Context) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getActionCountBase)
	var count sql.NullInt64
	err := row.Scan(&count)
	return count, err
}

const insertWorldEvent = `-- name: InsertWorldEvent :exec
INSERT INTO world_events
 (id, type, title, description, target_room, faction,
  payout_credits, payout_item_id, payout_item_name, payout_item_desc,
  status, expires_actions, created_actions, created_at)
 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWorldEventParams struct {
	ID             string         `json:"id"`
	Type           string         `json:"type"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	TargetRoom     string         `json:"target_room"`
	Faction        sql.NullString `json:"faction"`
	PayoutCredits  int64          `json:"payout_credits"`
	PayoutItemID   sql.NullString `json:"payout_item_id"`
	PayoutItemName sql.NullString `json:"payout_item_name"`
	PayoutItemDesc sql.NullString `json:"payout_item_desc"`
	Status         string         `json:"status"`
	ExpiresActions int64          `json:"expires_actions"`
	CreatedActions int64          `json:"created_actions"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) InsertWorldEvent(ctx context.Context, arg InsertWorldEventParams) error {
	_, err := q.db.ExecContext(ctx, insertWorldEvent,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.TargetRoom,
		arg.Faction,
		arg.PayoutCredits,
		arg.PayoutItemID,
		arg.PayoutItemName,
		arg.PayoutItemDesc,
		arg.Status,
		arg.ExpiresActions,
		arg.CreatedActions,
		arg.CreatedAt,
	)
	return err
}

const listBuildIDsInRoom = `-- name: ListBuildIDsInRoom :many
SELECT build_id FROM builds WHERE room_id = ?
`

func (q *Queries) ListBuildIDsInRoom(ctx context.Context, roomID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBuildIDsInRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var build_id string
		if err := rows.Scan(&build_id); err != nil {
			return nil, err
		}
		items = append(items, build_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredBaseRaids = `-- name: ListExpiredBaseRaids :many
SELECT id FROM world_events
WHERE type = 'base-raid' AND target_room = ? AND status = 'active'
AND (created_actions + expires_actions) <= ?
`

type ListExpiredBaseRaidsParams struct {
	TargetRoom     string `json:"target_room"`
	CreatedActions int64  `json:"created_actions"`
}

func (q *Queries) ListExpiredBaseRaids(ctx context.Context, arg ListExpiredBaseRaidsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredBaseRaids, arg.TargetRoom, arg.CreatedActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRandomChestItems = `-- name: ListRandomChestItems :many
SELECT item_id, item_name FROM chests WHERE room_id = ? ORDER BY RANDOM() LIMIT ?
`

type ListRandomChestItemsParams struct {
	RoomID string `json:"room_id"`
	Limit  int64  `json:"limit"`
}

type ListRandomChestItemsRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
}

func (q *Queries) ListRandomChestItems(ctx context.Context, arg ListRandomChestItemsParams) ([]ListRandomChestItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRandomChestItems, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRandomChestItemsRow{}
	for rows.Next() {
		var i ListRandomChestItemsRow
		if err := rows.Scan(&i.ItemID, &i.ItemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveWorldEvent = `-- name: ResolveWorldEvent :exec
UPDATE world_events SET status = 'resolved' WHERE id = ?
`

func (q *Queries) ResolveWorldEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resolveWorldEvent, id)
	return err
}
