// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: building.sql

package sqliteq

import (
	"context"
)

const countBuildsByType = `-- name: CountBuildsByType :one
SELECT COUNT(*) FROM builds WHERE room_id = ? AND build_id = ?
`

type CountBuildsByTypeParams struct {
	RoomID  string `json:"room_id"`
	BuildID string `json:"build_id"`
}

func (q *Queries) CountBuildsByType(ctx context.Context, arg CountBuildsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBuildsByType, arg.RoomID, arg.BuildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChestInRoom = `-- name: CountChestInRoom :one
SELECT COUNT(*) FROM builds WHERE room_id = ? AND build_id = 'chest'
`

func (q *Queries) CountChestInRoom(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChestInRoom, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChestItem = `-- name: DeleteChestItem :exec
DELETE FROM chests WHERE room_id = ? AND item_id = ?
`

type DeleteChestItemParams struct {
	RoomID string `json:"room_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteChestItem(ctx context.Context, arg DeleteChestItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteChestItem, arg.RoomID, arg.ItemID)
	return err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory WHERE item_id = ?
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteInventoryItem, itemID)
	return err
}

const getChestItem = `-- name: GetChestItem :one
SELECT item_name, item_desc FROM chests WHERE room_id = ? AND item_id = ?
`

type GetChestItemParams struct {
	RoomID string `json:"room_id"`
	ItemID string `json:"item_id"`
}

type GetChestItemRow struct {
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) GetChestItem(ctx context.Context, arg GetChestItemParams) (GetChestItemRow, error) {
	row := q.db.QueryRowContext(ctx, getChestItem, arg.RoomID, arg.ItemID)
	var i GetChestItemRow
	err := row.Scan(&i.ItemName, &i.ItemDesc)
	return i, err
}

const insertBuild = `-- name: InsertBuild :exec
INSERT INTO builds (room_id, build_id, name, desc, placed_at) VALUES (?, ?, ?, ?, ?)
`

type InsertBuildParams struct {
	RoomID   string `json:"room_id"`
	BuildID  string `json:"build_id"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
	PlacedAt int64  `json:"placed_at"`
}

func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) error {
	_, err := q.db.ExecContext(ctx, insertBuild,
		arg.RoomID,
		arg.BuildID,
		arg.Name,
		arg.Desc,
		arg.PlacedAt,
	)
	return err
}

const insertChestItem = `-- name: InsertChestItem :exec
INSERT OR IGNORE INTO chests (room_id, item_id, item_name, item_desc) VALUES (?, ?, ?, ?)
`

type InsertChestItemParams struct {
	RoomID   string `json:"room_id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) InsertChestItem(ctx context.Context, arg InsertChestItemParams) error {
	_, err := q.db.ExecContext(ctx, insertChestItem,
		arg.RoomID,
		arg.ItemID,
		arg.ItemName,
		arg.ItemDesc,
	)
	return err
}

const insertInventoryItem = `-- name: InsertInventoryItem :exec
INSERT OR IGNORE INTO inventory (item_id, item_name, item_desc) VALUES (?, ?, ?)
`

type InsertInventoryItemParams struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) InsertInventoryItem(ctx context.Context, arg InsertInventoryItemParams) error {
	_, err := q.db.ExecContext(ctx, insertInventoryItem, arg.ItemID, arg.ItemName, arg.ItemDesc)
	return err
}

const listChestItems = `-- name: ListChestItems :many
SELECT item_id, item_name FROM chests WHERE room_id = ?
`

type ListChestItemsRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
}

func (q *Queries) ListChestItems(ctx context.Context, roomID string) ([]ListChestItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChestItems, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChestItemsRow{}
	for rows.Next() {
		var i ListChestItemsRow
		if err := rows.Scan(&i.ItemID, &i.ItemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
