// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crafting.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const countPlayerFlag = `-- name: CountPlayerFlag :one
SELECT COUNT(*) FROM player_flags WHERE flag = ?
`

func (q *Queries) CountPlayerFlag(ctx context.Context, flag string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayerFlag, flag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnlockedRecipe = `-- name: CountUnlockedRecipe :one
SELECT COUNT(*) FROM unlocked_recipes WHERE recipe_id = ?
`

func (q *Queries) CountUnlockedRecipe(ctx context.Context, recipeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnlockedRecipe, recipeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOneInventoryItem = `-- name: DeleteOneInventoryItem :exec
DELETE FROM inventory WHERE rowid IN (SELECT inventory.rowid FROM inventory WHERE inventory.item_id = ? LIMIT 1)
`

func (q *Queries) DeleteOneInventoryItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteOneInventoryItem, itemID)
	return err
}

const insertInventoryItemCraft = `-- name: InsertInventoryItemCraft :exec
INSERT OR IGNORE INTO inventory (item_id, item_name, item_desc) VALUES (?, ?, ?)
`

type InsertInventoryItemCraftParams struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) InsertInventoryItemCraft(ctx context.Context, arg InsertInventoryItemCraftParams) error {
	_, err := q.db.ExecContext(ctx, insertInventoryItemCraft, arg.ItemID, arg.ItemName, arg.ItemDesc)
	return err
}

const isRecipeUnlocked = `-- name: IsRecipeUnlocked :one
SELECT COUNT(*) FROM unlocked_recipes WHERE recipe_id = ?
`

func (q *Queries) IsRecipeUnlocked(ctx context.Context, recipeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isRecipeUnlocked, recipeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setPlayerFlag = `-- name: SetPlayerFlag :exec
INSERT OR IGNORE INTO player_flags (flag) VALUES (?)
`

func (q *Queries) SetPlayerFlag(ctx context.Context, flag string) error {
	_, err := q.db.ExecContext(ctx, setPlayerFlag, flag)
	return err
}

const unlockRecipe = `-- name: UnlockRecipe :exec
INSERT OR IGNORE INTO unlocked_recipes (recipe_id, unlocked_at) VALUES (?, ?)
`

type UnlockRecipeParams struct {
	RecipeID   string        `json:"recipe_id"`
	UnlockedAt sql.NullInt64 `json:"unlocked_at"`
}

func (q *Queries) UnlockRecipe(ctx context.Context, arg UnlockRecipeParams) error {
	_, err := q.db.ExecContext(ctx, unlockRecipe, arg.RecipeID, arg.UnlockedAt)
	return err
}
