// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credits.sql

package sqliteq

import (
	"context"
)

const getCredits = `-- name: GetCredits :one
SELECT credits FROM player_credits WHERE id = 1
`

func (q *Queries) GetCredits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCredits)
	var credits int64
	err := row.Scan(&credits)
	return credits, err
}

const upsertCredits = `-- name: UpsertCredits :exec
INSERT INTO player_credits (id, credits) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET credits = credits + excluded.credits
`

func (q *Queries) UpsertCredits(ctx context.Context, credits int64) error {
	_, err := q.db.ExecContext(ctx, upsertCredits, credits)
	return err
}
