// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enchanting.sql

package sqliteq

import (
	"context"
)

const addEnchantingXP = `-- name: AddEnchantingXP :exec
UPDATE enchanting_xp
SET xp    = xp + ?,
    level = MIN(MAX(1, (xp + ?) / 100), 30)
WHERE id = 1
`

type AddEnchantingXPParams struct {
	Xp   int64 `json:"xp"`
	Xp_2 int64 `json:"xp_2"`
}

func (q *Queries) AddEnchantingXP(ctx context.Context, arg AddEnchantingXPParams) error {
	_, err := q.db.ExecContext(ctx, addEnchantingXP, arg.Xp, arg.Xp_2)
	return err
}

const applyEnchant = `-- name: ApplyEnchant :exec
INSERT INTO enchants (item_id, enchant_id, level, applied_at) VALUES (?, ?, ?, ?)
ON CONFLICT(item_id, enchant_id) DO UPDATE SET level = excluded.level, applied_at = excluded.applied_at
`

type ApplyEnchantParams struct {
	ItemID    string `json:"item_id"`
	EnchantID string `json:"enchant_id"`
	Level     int64  `json:"level"`
	AppliedAt int64  `json:"applied_at"`
}

func (q *Queries) ApplyEnchant(ctx context.Context, arg ApplyEnchantParams) error {
	_, err := q.db.ExecContext(ctx, applyEnchant,
		arg.ItemID,
		arg.EnchantID,
		arg.Level,
		arg.AppliedAt,
	)
	return err
}

const getEnchantingXPState = `-- name: GetEnchantingXPState :one
SELECT xp, level FROM enchanting_xp WHERE id = 1
`

type GetEnchantingXPStateRow struct {
	Xp    int64 `json:"xp"`
	Level int64 `json:"level"`
}

func (q *Queries) GetEnchantingXPState(ctx context.Context) (GetEnchantingXPStateRow, error) {
	row := q.db.QueryRowContext(ctx, getEnchantingXPState)
	var i GetEnchantingXPStateRow
	err := row.Scan(&i.Xp, &i.Level)
	return i, err
}

const listEnchants = `-- name: ListEnchants :many
SELECT item_id, enchant_id, level FROM enchants WHERE item_id = ?
`

type ListEnchantsRow struct {
	ItemID    string `json:"item_id"`
	EnchantID string `json:"enchant_id"`
	Level     int64  `json:"level"`
}

func (q *Queries) ListEnchants(ctx context.Context, itemID string) ([]ListEnchantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnchants, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnchantsRow{}
	for rows.Next() {
		var i ListEnchantsRow
		if err := rows.Scan(&i.ItemID, &i.EnchantID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
