// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enchant_cmd.sql

package sqliteq

import (
	"context"
)

const countEnchantingTable = `-- name: CountEnchantingTable :one
SELECT COUNT(*) FROM builds WHERE room_id = ? AND build_id = 'enchanting-table'
`

func (q *Queries) CountEnchantingTable(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnchantingTable, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deductEnchantingXP = `-- name: DeductEnchantingXP :exec
UPDATE enchanting_xp SET xp = xp - ? WHERE id = 1
`

func (q *Queries) DeductEnchantingXP(ctx context.Context, xp int64) error {
	_, err := q.db.ExecContext(ctx, deductEnchantingXP, xp)
	return err
}
