// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: factions.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const countFactionMembers = `-- name: CountFactionMembers :one
SELECT COUNT(*) FROM faction_members
`

func (q *Queries) CountFactionMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFactionMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFaction = `-- name: CreateFaction :exec
INSERT INTO player_faction (id, faction_id, faction_name, agenda, hideout_room_id, credits, created_at)
VALUES (1, ?, ?, ?, '', 0, ?)
`

type CreateFactionParams struct {
	FactionID   string         `json:"faction_id"`
	FactionName string         `json:"faction_name"`
	Agenda      sql.NullString `json:"agenda"`
	CreatedAt   int64          `json:"created_at"`
}

func (q *Queries) CreateFaction(ctx context.Context, arg CreateFactionParams) error {
	_, err := q.db.ExecContext(ctx, createFaction,
		arg.FactionID,
		arg.FactionName,
		arg.Agenda,
		arg.CreatedAt,
	)
	return err
}

const factionExists = `-- name: FactionExists :one
SELECT id FROM player_faction WHERE id = 1
`

func (q *Queries) FactionExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, factionExists)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFaction = `-- name: GetFaction :one
SELECT faction_id, faction_name, agenda, hideout_room_id, credits, created_at
FROM player_faction WHERE id = 1
`

type GetFactionRow struct {
	FactionID     string         `json:"faction_id"`
	FactionName   string         `json:"faction_name"`
	Agenda        sql.NullString `json:"agenda"`
	HideoutRoomID sql.NullString `json:"hideout_room_id"`
	Credits       int64          `json:"credits"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) GetFaction(ctx context.Context) (GetFactionRow, error) {
	row := q.db.QueryRowContext(ctx, getFaction)
	var i GetFactionRow
	err := row.Scan(
		&i.FactionID,
		&i.FactionName,
		&i.Agenda,
		&i.HideoutRoomID,
		&i.Credits,
		&i.CreatedAt,
	)
	return i, err
}

const getFactionMember = `-- name: GetFactionMember :one
SELECT npc_id FROM faction_members WHERE npc_id = ?
`

func (q *Queries) GetFactionMember(ctx context.Context, npcID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFactionMember, npcID)
	var npc_id string
	err := row.Scan(&npc_id)
	return npc_id, err
}

const insertFactionMember = `-- name: InsertFactionMember :exec
INSERT INTO faction_members (npc_id, npc_name, npc_desc, role, stationed_room, loyalty, recruited_at)
VALUES (?, ?, ?, ?, '', 50, ?)
`

type InsertFactionMemberParams struct {
	NpcID       string         `json:"npc_id"`
	NpcName     string         `json:"npc_name"`
	NpcDesc     sql.NullString `json:"npc_desc"`
	Role        string         `json:"role"`
	RecruitedAt int64          `json:"recruited_at"`
}

func (q *Queries) InsertFactionMember(ctx context.Context, arg InsertFactionMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertFactionMember,
		arg.NpcID,
		arg.NpcName,
		arg.NpcDesc,
		arg.Role,
		arg.RecruitedAt,
	)
	return err
}

const listFactionMembers = `-- name: ListFactionMembers :many
SELECT npc_id, npc_name, npc_desc, role, stationed_room, loyalty, recruited_at
FROM faction_members
`

func (q *Queries) ListFactionMembers(ctx context.Context) ([]FactionMember, error) {
	rows, err := q.db.QueryContext(ctx, listFactionMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FactionMember{}
	for rows.Next() {
		var i FactionMember
		if err := rows.Scan(
			&i.NpcID,
			&i.NpcName,
			&i.NpcDesc,
			&i.Role,
			&i.StationedRoom,
			&i.Loyalty,
			&i.RecruitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFactionHideout = `-- name: SetFactionHideout :exec
UPDATE player_faction SET hideout_room_id = ? WHERE id = 1
`

func (q *Queries) SetFactionHideout(ctx context.Context, hideoutRoomID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, setFactionHideout, hideoutRoomID)
	return err
}
