// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: general.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const countChestItemsInRoom = `-- name: CountChestItemsInRoom :one
SELECT COUNT(*) FROM chests WHERE room_id = ?
`

func (q *Queries) CountChestItemsInRoom(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChestItemsInRoom, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCollectedShards = `-- name: CountCollectedShards :one
SELECT COUNT(*) FROM crystal_shards WHERE collected = 1
`

func (q *Queries) CountCollectedShards(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCollectedShards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalShards = `-- name: CountTotalShards :one
SELECT COUNT(*) FROM crystal_shards
`

func (q *Queries) CountTotalShards(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalShards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActionCountGeneral = `-- name: GetActionCountGeneral :one
SELECT count FROM player_actions WHERE id = 1
`

func (q *Queries) GetActionCountGeneral(ctx context.Context) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getActionCountGeneral)
	var count sql.NullInt64
	err := row.Scan(&count)
	return count, err
}

const listBuildsInRoom = `-- name: ListBuildsInRoom :many
SELECT build_id, name FROM builds WHERE room_id = ? ORDER BY placed_at
`

type ListBuildsInRoomRow struct {
	BuildID string `json:"build_id"`
	Name    string `json:"name"`
}

func (q *Queries) ListBuildsInRoom(ctx context.Context, roomID string) ([]ListBuildsInRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, listBuildsInRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildsInRoomRow{}
	for rows.Next() {
		var i ListBuildsInRoomRow
		if err := rows.Scan(&i.BuildID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighRepFactions = `-- name: ListHighRepFactions :many
SELECT faction, value FROM player_reputation WHERE value >= 3
`

func (q *Queries) ListHighRepFactions(ctx context.Context) ([]PlayerReputation, error) {
	rows, err := q.db.QueryContext(ctx, listHighRepFactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerReputation{}
	for rows.Next() {
		var i PlayerReputation
		if err := rows.Scan(&i.Faction, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReputations = `-- name: ListReputations :many
SELECT faction, value FROM player_reputation
`

func (q *Queries) ListReputations(ctx context.Context) ([]PlayerReputation, error) {
	rows, err := q.db.QueryContext(ctx, listReputations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerReputation{}
	for rows.Next() {
		var i PlayerReputation
		if err := rows.Scan(&i.Faction, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFactionMemberStation = `-- name: UpdateFactionMemberStation :exec
UPDATE faction_members SET stationed_room = ? WHERE npc_id = ?
`

type UpdateFactionMemberStationParams struct {
	StationedRoom sql.NullString `json:"stationed_room"`
	NpcID         string         `json:"npc_id"`
}

func (q *Queries) UpdateFactionMemberStation(ctx context.Context, arg UpdateFactionMemberStationParams) error {
	_, err := q.db.ExecContext(ctx, updateFactionMemberStation, arg.StationedRoom, arg.NpcID)
	return err
}
