// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hacking.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const deleteVulnWindow = `-- name: DeleteVulnWindow :exec
DELETE FROM vuln_windows WHERE system_id = ?
`

func (q *Queries) DeleteVulnWindow(ctx context.Context, systemID string) error {
	_, err := q.db.ExecContext(ctx, deleteVulnWindow, systemID)
	return err
}

const getSystemAlert = `-- name: GetSystemAlert :one
SELECT alert FROM system_state WHERE room_id = ? AND system_id = ?
`

type GetSystemAlertParams struct {
	RoomID   string `json:"room_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) GetSystemAlert(ctx context.Context, arg GetSystemAlertParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSystemAlert, arg.RoomID, arg.SystemID)
	var alert int64
	err := row.Scan(&alert)
	return alert, err
}

const getSystemAlertForHackMulti = `-- name: GetSystemAlertForHackMulti :one
SELECT alert FROM system_state WHERE room_id = ? AND system_id = ?
`

type GetSystemAlertForHackMultiParams struct {
	RoomID   string `json:"room_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) GetSystemAlertForHackMulti(ctx context.Context, arg GetSystemAlertForHackMultiParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSystemAlertForHackMulti, arg.RoomID, arg.SystemID)
	var alert int64
	err := row.Scan(&alert)
	return alert, err
}

const getSystemHacked = `-- name: GetSystemHacked :one
SELECT hacked FROM system_state WHERE room_id = ? AND system_id = ?
`

type GetSystemHackedParams struct {
	RoomID   string `json:"room_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) GetSystemHacked(ctx context.Context, arg GetSystemHackedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSystemHacked, arg.RoomID, arg.SystemID)
	var hacked int64
	err := row.Scan(&hacked)
	return hacked, err
}

const getVulnWindow = `-- name: GetVulnWindow :one
SELECT bonus, expires_action FROM vuln_windows WHERE system_id = ?
`

type GetVulnWindowRow struct {
	Bonus         sql.NullInt64 `json:"bonus"`
	ExpiresAction sql.NullInt64 `json:"expires_action"`
}

func (q *Queries) GetVulnWindow(ctx context.Context, systemID string) (GetVulnWindowRow, error) {
	row := q.db.QueryRowContext(ctx, getVulnWindow, systemID)
	var i GetVulnWindowRow
	err := row.Scan(&i.Bonus, &i.ExpiresAction)
	return i, err
}

const incrementSystemAlert = `-- name: IncrementSystemAlert :exec
INSERT INTO system_state (room_id, system_id, alert, hacked) VALUES (?, ?, 1, 0)
ON CONFLICT(room_id, system_id) DO UPDATE SET alert = alert + 1
`

type IncrementSystemAlertParams struct {
	RoomID   string `json:"room_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) IncrementSystemAlert(ctx context.Context, arg IncrementSystemAlertParams) error {
	_, err := q.db.ExecContext(ctx, incrementSystemAlert, arg.RoomID, arg.SystemID)
	return err
}

const insertBounty = `-- name: InsertBounty :exec
INSERT OR REPLACE INTO bounties (room_id, npc_id, created_at) VALUES (?, ?, ?)
`

type InsertBountyParams struct {
	RoomID    string         `json:"room_id"`
	NpcID     sql.NullString `json:"npc_id"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

func (q *Queries) InsertBounty(ctx context.Context, arg InsertBountyParams) error {
	_, err := q.db.ExecContext(ctx, insertBounty, arg.RoomID, arg.NpcID, arg.CreatedAt)
	return err
}

const markSystemHacked = `-- name: MarkSystemHacked :exec
INSERT INTO system_state (room_id, system_id, hacked, alert) VALUES (?, ?, 1, 0)
ON CONFLICT(room_id, system_id) DO UPDATE SET hacked = 1
`

type MarkSystemHackedParams struct {
	RoomID   string `json:"room_id"`
	SystemID string `json:"system_id"`
}

func (q *Queries) MarkSystemHacked(ctx context.Context, arg MarkSystemHackedParams) error {
	_, err := q.db.ExecContext(ctx, markSystemHacked, arg.RoomID, arg.SystemID)
	return err
}

const setVulnWindow = `-- name: SetVulnWindow :exec
INSERT OR REPLACE INTO vuln_windows (system_id, bonus, expires_action) VALUES (?, ?, ?)
`

type SetVulnWindowParams struct {
	SystemID      string        `json:"system_id"`
	Bonus         sql.NullInt64 `json:"bonus"`
	ExpiresAction sql.NullInt64 `json:"expires_action"`
}

func (q *Queries) SetVulnWindow(ctx context.Context, arg SetVulnWindowParams) error {
	_, err := q.db.ExecContext(ctx, setVulnWindow, arg.SystemID, arg.Bonus, arg.ExpiresAction)
	return err
}

const upsertSystemAlert = `-- name: UpsertSystemAlert :exec
INSERT INTO system_state (room_id, system_id, intrusion, alert) VALUES (?, ?, 0, ?)
ON CONFLICT(room_id, system_id) DO UPDATE SET alert = excluded.alert
`

type UpsertSystemAlertParams struct {
	RoomID   string `json:"room_id"`
	SystemID string `json:"system_id"`
	Alert    int64  `json:"alert"`
}

func (q *Queries) UpsertSystemAlert(ctx context.Context, arg UpsertSystemAlertParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemAlert, arg.RoomID, arg.SystemID, arg.Alert)
	return err
}
