// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mining.sql

package sqliteq

import (
	"context"
)

const bumpActions = `-- name: BumpActions :exec
INSERT INTO player_actions (id, count) VALUES (1, 1)
ON CONFLICT(id) DO UPDATE SET count = count + 1
`

func (q *Queries) BumpActions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, bumpActions)
	return err
}

const clearResourceDepletion = `-- name: ClearResourceDepletion :exec
UPDATE room_resources SET depleted = 0 WHERE room_id = ? AND resource_id = ?
`

type ClearResourceDepletionParams struct {
	RoomID     string `json:"room_id"`
	ResourceID string `json:"resource_id"`
}

func (q *Queries) ClearResourceDepletion(ctx context.Context, arg ClearResourceDepletionParams) error {
	_, err := q.db.ExecContext(ctx, clearResourceDepletion, arg.RoomID, arg.ResourceID)
	return err
}

const countReadyCrops = `-- name: CountReadyCrops :one
SELECT COUNT(*) FROM crops WHERE room_id = ? AND seed_id = ? AND ready_at_action <= ? AND harvested = 0
`

type CountReadyCropsParams struct {
	RoomID        string `json:"room_id"`
	SeedID        string `json:"seed_id"`
	ReadyAtAction int64  `json:"ready_at_action"`
}

func (q *Queries) CountReadyCrops(ctx context.Context, arg CountReadyCropsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReadyCrops, arg.RoomID, arg.SeedID, arg.ReadyAtAction)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const depleteResource = `-- name: DepleteResource :exec
INSERT INTO room_resources (room_id, resource_id, depleted, depleted_at_action) VALUES (?, ?, 1, ?)
ON CONFLICT(room_id, resource_id) DO UPDATE SET depleted = 1, depleted_at_action = excluded.depleted_at_action
`

type DepleteResourceParams struct {
	RoomID           string `json:"room_id"`
	ResourceID       string `json:"resource_id"`
	DepletedAtAction int64  `json:"depleted_at_action"`
}

func (q *Queries) DepleteResource(ctx context.Context, arg DepleteResourceParams) error {
	_, err := q.db.ExecContext(ctx, depleteResource, arg.RoomID, arg.ResourceID, arg.DepletedAtAction)
	return err
}

const getResourceState = `-- name: GetResourceState :one
SELECT depleted, depleted_at_action FROM room_resources WHERE room_id = ? AND resource_id = ?
`

type GetResourceStateParams struct {
	RoomID     string `json:"room_id"`
	ResourceID string `json:"resource_id"`
}

type GetResourceStateRow struct {
	Depleted         int64 `json:"depleted"`
	DepletedAtAction int64 `json:"depleted_at_action"`
}

func (q *Queries) GetResourceState(ctx context.Context, arg GetResourceStateParams) (GetResourceStateRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceState, arg.RoomID, arg.ResourceID)
	var i GetResourceStateRow
	err := row.Scan(&i.Depleted, &i.DepletedAtAction)
	return i, err
}

const harvestCrops = `-- name: HarvestCrops :exec
UPDATE crops SET harvested = 1 WHERE room_id = ? AND seed_id = ? AND ready_at_action <= ? AND harvested = 0
`

type HarvestCropsParams struct {
	RoomID        string `json:"room_id"`
	SeedID        string `json:"seed_id"`
	ReadyAtAction int64  `json:"ready_at_action"`
}

func (q *Queries) HarvestCrops(ctx context.Context, arg HarvestCropsParams) error {
	_, err := q.db.ExecContext(ctx, harvestCrops, arg.RoomID, arg.SeedID, arg.ReadyAtAction)
	return err
}

const insertCrop = `-- name: InsertCrop :exec
INSERT INTO crops (room_id, slot, seed_id, planted_at_action, ready_at_action) VALUES (?, ?, ?, ?, ?)
`

type InsertCropParams struct {
	RoomID          string `json:"room_id"`
	Slot            int64  `json:"slot"`
	SeedID          string `json:"seed_id"`
	PlantedAtAction int64  `json:"planted_at_action"`
	ReadyAtAction   int64  `json:"ready_at_action"`
}

func (q *Queries) InsertCrop(ctx context.Context, arg InsertCropParams) error {
	_, err := q.db.ExecContext(ctx, insertCrop,
		arg.RoomID,
		arg.Slot,
		arg.SeedID,
		arg.PlantedAtAction,
		arg.ReadyAtAction,
	)
	return err
}

const listActiveCropSlots = `-- name: ListActiveCropSlots :many
SELECT slot FROM crops WHERE room_id = ? AND harvested = 0
`

func (q *Queries) ListActiveCropSlots(ctx context.Context, roomID string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCropSlots, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var slot int64
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyCrops = `-- name: ListReadyCrops :many
SELECT seed_id FROM crops WHERE room_id = ? AND ready_at_action <= ? AND harvested = 0
`

type ListReadyCropsParams struct {
	RoomID        string `json:"room_id"`
	ReadyAtAction int64  `json:"ready_at_action"`
}

func (q *Queries) ListReadyCrops(ctx context.Context, arg ListReadyCropsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listReadyCrops, arg.RoomID, arg.ReadyAtAction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var seed_id string
		if err := rows.Scan(&seed_id); err != nil {
			return nil, err
		}
		items = append(items, seed_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
