// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliteq

import (
	"database/sql"
)

type ArenaSession struct {
	ID             string `json:"id"`
	GameType       string `json:"game_type"`
	Phase          string `json:"phase"`
	Wave           int64  `json:"wave"`
	EnemiesJson    string `json:"enemies_json"`
	RewardCredits  int64  `json:"reward_credits"`
	RewardItemID   string `json:"reward_item_id"`
	RewardItemName string `json:"reward_item_name"`
	RewardItemDesc string `json:"reward_item_desc"`
	Status         string `json:"status"`
	StartedAt      int64  `json:"started_at"`
}

type Bounty struct {
	RoomID    string         `json:"room_id"`
	NpcID     sql.NullString `json:"npc_id"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

type Build struct {
	ID       int64  `json:"id"`
	RoomID   string `json:"room_id"`
	BuildID  string `json:"build_id"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
	PlacedAt int64  `json:"placed_at"`
}

type Chest struct {
	RoomID   string `json:"room_id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

type Crop struct {
	RoomID          string `json:"room_id"`
	Slot            int64  `json:"slot"`
	SeedID          string `json:"seed_id"`
	PlantedAtAction int64  `json:"planted_at_action"`
	ReadyAtAction   int64  `json:"ready_at_action"`
	Harvested       int64  `json:"harvested"`
}

type CrystalShard struct {
	ShardID     string `json:"shard_id"`
	Biome       string `json:"biome"`
	Collected   int64  `json:"collected"`
	CollectedAt int64  `json:"collected_at"`
}

type DeathPile struct {
	ID       int64  `json:"id"`
	RoomID   string `json:"room_id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
	DiedAt   int64  `json:"died_at"`
}

type Enchant struct {
	ItemID    string `json:"item_id"`
	EnchantID string `json:"enchant_id"`
	Level     int64  `json:"level"`
	AppliedAt int64  `json:"applied_at"`
}

type EnchantingXp struct {
	ID    int64 `json:"id"`
	Xp    int64 `json:"xp"`
	Level int64 `json:"level"`
}

type EquippedArmor struct {
	ID       int64  `json:"id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	Defense  int64  `json:"defense"`
}

type FactionMember struct {
	NpcID         string         `json:"npc_id"`
	NpcName       string         `json:"npc_name"`
	NpcDesc       sql.NullString `json:"npc_desc"`
	Role          string         `json:"role"`
	StationedRoom sql.NullString `json:"stationed_room"`
	Loyalty       int64          `json:"loyalty"`
	RecruitedAt   int64          `json:"recruited_at"`
}

type GeneratedContent struct {
	PromptHash string `json:"prompt_hash"`
	Type       string `json:"type"`
	YamlBlob   string `json:"yaml_blob"`
	CreatedAt  int64  `json:"created_at"`
}

type HideoutUpgrade struct {
	UpgradeID   string `json:"upgrade_id"`
	InstalledAt int64  `json:"installed_at"`
}

type Inventory struct {
	ID       int64  `json:"id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

type ItemMod struct {
	ItemInstance string         `json:"item_instance"`
	ModID        sql.NullString `json:"mod_id"`
	AppliedAt    sql.NullInt64  `json:"applied_at"`
}

type LockState struct {
	LockID   string `json:"lock_id"`
	Unlocked int64  `json:"unlocked"`
}

type NpcMemory struct {
	NpcID  string `json:"npc_id"`
	Action string `json:"action"`
	Ts     int64  `json:"ts"`
}

type NpcState struct {
	RoomID string `json:"room_id"`
	NpcID  string `json:"npc_id"`
	Hp     int64  `json:"hp"`
	Alive  int64  `json:"alive"`
}

type Player struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	RoomID string `json:"room_id"`
	Hp     int64  `json:"hp"`
	MaxHp  int64  `json:"max_hp"`
	World  string `json:"world"`
}

type PlayerAction struct {
	ID    int64         `json:"id"`
	Count sql.NullInt64 `json:"count"`
}

type PlayerAugment struct {
	Skill       sql.NullString `json:"skill"`
	Bonus       sql.NullInt64  `json:"bonus"`
	InstalledAt sql.NullInt64  `json:"installed_at"`
}

type PlayerCredit struct {
	ID      int64 `json:"id"`
	Credits int64 `json:"credits"`
}

type PlayerFaction struct {
	ID            int64          `json:"id"`
	FactionID     string         `json:"faction_id"`
	FactionName   string         `json:"faction_name"`
	Agenda        sql.NullString `json:"agenda"`
	HideoutRoomID sql.NullString `json:"hideout_room_id"`
	Credits       int64          `json:"credits"`
	CreatedAt     int64          `json:"created_at"`
}

type PlayerFlag struct {
	Flag string `json:"flag"`
}

type PlayerReputation struct {
	Faction string `json:"faction"`
	Value   int64  `json:"value"`
}

type PlayerSkill struct {
	Skill string `json:"skill"`
	Level int64  `json:"level"`
	Xp    int64  `json:"xp"`
}

type PlayerStealth struct {
	ID       int64  `json:"id"`
	Level    int64  `json:"level"`
	Disguise string `json:"disguise"`
}

type Quest struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	ObjType        string         `json:"obj_type"`
	ObjTarget      string         `json:"obj_target"`
	ObjRoom        sql.NullString `json:"obj_room"`
	ObjCount       int64          `json:"obj_count"`
	ObjProgress    int64          `json:"obj_progress"`
	RewardCredits  int64          `json:"reward_credits"`
	RewardXpSkill  sql.NullString `json:"reward_xp_skill"`
	RewardXpAmount int64          `json:"reward_xp_amount"`
	RewardItemID   sql.NullString `json:"reward_item_id"`
	RewardItemName sql.NullString `json:"reward_item_name"`
	RewardItemDesc sql.NullString `json:"reward_item_desc"`
	GiverNpcID     sql.NullString `json:"giver_npc_id"`
	AcceptedAt     int64          `json:"accepted_at"`
	NextQuestID    string         `json:"next_quest_id"`
}

type RoomResource struct {
	RoomID           string `json:"room_id"`
	ResourceID       string `json:"resource_id"`
	Depleted         int64  `json:"depleted"`
	DepletedAtAction int64  `json:"depleted_at_action"`
}

type SystemState struct {
	RoomID    string  `json:"room_id"`
	SystemID  string  `json:"system_id"`
	Intrusion float64 `json:"intrusion"`
	Alert     int64   `json:"alert"`
	Hacked    int64   `json:"hacked"`
}

type UnlockedRecipe struct {
	RecipeID   string        `json:"recipe_id"`
	UnlockedAt sql.NullInt64 `json:"unlocked_at"`
}

type Visited struct {
	RoomID string `json:"room_id"`
}

type VulnWindow struct {
	SystemID      string        `json:"system_id"`
	Bonus         sql.NullInt64 `json:"bonus"`
	ExpiresAction sql.NullInt64 `json:"expires_action"`
}

type WeatherState struct {
	Biome         string `json:"biome"`
	Condition     string `json:"condition"`
	ExpiresAction int64  `json:"expires_action"`
}

type WorldEvent struct {
	ID             string         `json:"id"`
	Type           string         `json:"type"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	TargetRoom     string         `json:"target_room"`
	Faction        sql.NullString `json:"faction"`
	PayoutCredits  int64          `json:"payout_credits"`
	PayoutItemID   sql.NullString `json:"payout_item_id"`
	PayoutItemName sql.NullString `json:"payout_item_name"`
	PayoutItemDesc sql.NullString `json:"payout_item_desc"`
	Status         string         `json:"status"`
	ExpiresActions int64          `json:"expires_actions"`
	CreatedActions int64          `json:"created_actions"`
	CreatedAt      int64          `json:"created_at"`
}
