// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placeholder.sql

package sqliteq

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
