// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const addItem = `-- name: AddItem :exec
INSERT OR IGNORE INTO inventory (item_id, item_name, item_desc) VALUES (?, ?, ?)
`

type AddItemParams struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) error {
	_, err := q.db.ExecContext(ctx, addItem, arg.ItemID, arg.ItemName, arg.ItemDesc)
	return err
}

const anyDeathPile = `-- name: AnyDeathPile :one
SELECT room_id, COUNT(*) as count FROM death_pile GROUP BY room_id ORDER BY MAX(died_at) DESC, MAX(id) DESC LIMIT 1
`

type AnyDeathPileRow struct {
	RoomID string `json:"room_id"`
	Count  int64  `json:"count"`
}

func (q *Queries) AnyDeathPile(ctx context.Context) (AnyDeathPileRow, error) {
	row := q.db.QueryRowContext(ctx, anyDeathPile)
	var i AnyDeathPileRow
	err := row.Scan(&i.RoomID, &i.Count)
	return i, err
}

const clearInventory = `-- name: ClearInventory :exec
DELETE FROM inventory
`

func (q *Queries) ClearInventory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearInventory)
	return err
}

const deleteDeathPile = `-- name: DeleteDeathPile :exec
DELETE FROM death_pile WHERE room_id = ?
`

func (q *Queries) DeleteDeathPile(ctx context.Context, roomID string) error {
	_, err := q.db.ExecContext(ctx, deleteDeathPile, roomID)
	return err
}

const equipArmor = `-- name: EquipArmor :exec
INSERT OR REPLACE INTO equipped_armor (id, item_id, item_name, defense) VALUES (1, ?, ?, ?)
`

type EquipArmorParams struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	Defense  int64  `json:"defense"`
}

func (q *Queries) EquipArmor(ctx context.Context, arg EquipArmorParams) error {
	_, err := q.db.ExecContext(ctx, equipArmor, arg.ItemID, arg.ItemName, arg.Defense)
	return err
}

const getActionCount = `-- name: GetActionCount :one
SELECT count FROM player_actions WHERE id = 1
`

func (q *Queries) GetActionCount(ctx context.Context) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getActionCount)
	var count sql.NullInt64
	err := row.Scan(&count)
	return count, err
}

const getDeathPile = `-- name: GetDeathPile :many
SELECT item_id, item_name, item_desc FROM death_pile WHERE room_id = ?
`

type GetDeathPileRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) GetDeathPile(ctx context.Context, roomID string) ([]GetDeathPileRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeathPile, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDeathPileRow{}
	for rows.Next() {
		var i GetDeathPileRow
		if err := rows.Scan(&i.ItemID, &i.ItemName, &i.ItemDesc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquippedArmor = `-- name: GetEquippedArmor :one
SELECT item_id, item_name, defense FROM equipped_armor WHERE id = 1
`

type GetEquippedArmorRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	Defense  int64  `json:"defense"`
}

func (q *Queries) GetEquippedArmor(ctx context.Context) (GetEquippedArmorRow, error) {
	row := q.db.QueryRowContext(ctx, getEquippedArmor)
	var i GetEquippedArmorRow
	err := row.Scan(&i.ItemID, &i.ItemName, &i.Defense)
	return i, err
}

const getNPCState = `-- name: GetNPCState :one
SELECT hp, alive FROM npc_state WHERE room_id = ? AND npc_id = ?
`

type GetNPCStateParams struct {
	RoomID string `json:"room_id"`
	NpcID  string `json:"npc_id"`
}

type GetNPCStateRow struct {
	Hp    int64 `json:"hp"`
	Alive int64 `json:"alive"`
}

func (q *Queries) GetNPCState(ctx context.Context, arg GetNPCStateParams) (GetNPCStateRow, error) {
	row := q.db.QueryRowContext(ctx, getNPCState, arg.RoomID, arg.NpcID)
	var i GetNPCStateRow
	err := row.Scan(&i.Hp, &i.Alive)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT name, room_id, hp, max_hp, world FROM player WHERE id = 1
`

type GetPlayerRow struct {
	Name   string `json:"name"`
	RoomID string `json:"room_id"`
	Hp     int64  `json:"hp"`
	MaxHp  int64  `json:"max_hp"`
	World  string `json:"world"`
}

func (q *Queries) GetPlayer(ctx context.Context) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer)
	var i GetPlayerRow
	err := row.Scan(
		&i.Name,
		&i.RoomID,
		&i.Hp,
		&i.MaxHp,
		&i.World,
	)
	return i, err
}

const hasVisited = `-- name: HasVisited :one
SELECT room_id FROM visited WHERE room_id = ?
`

func (q *Queries) HasVisited(ctx context.Context, roomID string) (string, error) {
	row := q.db.QueryRowContext(ctx, hasVisited, roomID)
	var room_id string
	err := row.Scan(&room_id)
	return room_id, err
}

const insertDeathPile = `-- name: InsertDeathPile :exec
INSERT INTO death_pile (room_id, item_id, item_name, item_desc, died_at) VALUES (?, ?, ?, ?, ?)
`

type InsertDeathPileParams struct {
	RoomID   string `json:"room_id"`
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
	DiedAt   int64  `json:"died_at"`
}

func (q *Queries) InsertDeathPile(ctx context.Context, arg InsertDeathPileParams) error {
	_, err := q.db.ExecContext(ctx, insertDeathPile,
		arg.RoomID,
		arg.ItemID,
		arg.ItemName,
		arg.ItemDesc,
		arg.DiedAt,
	)
	return err
}

const listInventory = `-- name: ListInventory :many
SELECT item_id, item_name, item_desc FROM inventory
`

type ListInventoryRow struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) ListInventory(ctx context.Context) ([]ListInventoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(&i.ItemID, &i.ItemName, &i.ItemDesc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShardCollected = `-- name: MarkShardCollected :exec
UPDATE crystal_shards SET collected = 1, collected_at = ? WHERE shard_id = ?
`

type MarkShardCollectedParams struct {
	CollectedAt int64  `json:"collected_at"`
	ShardID     string `json:"shard_id"`
}

func (q *Queries) MarkShardCollected(ctx context.Context, arg MarkShardCollectedParams) error {
	_, err := q.db.ExecContext(ctx, markShardCollected, arg.CollectedAt, arg.ShardID)
	return err
}

const markVisited = `-- name: MarkVisited :exec
INSERT OR IGNORE INTO visited (room_id) VALUES (?)
`

func (q *Queries) MarkVisited(ctx context.Context, roomID string) error {
	_, err := q.db.ExecContext(ctx, markVisited, roomID)
	return err
}

const removeItem = `-- name: RemoveItem :execresult
DELETE FROM inventory WHERE item_id = ?
`

func (q *Queries) RemoveItem(ctx context.Context, itemID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeItem, itemID)
}

const savePlayer = `-- name: SavePlayer :exec
UPDATE player SET room_id = ?, hp = ?, max_hp = ?, world = ? WHERE id = 1
`

type SavePlayerParams struct {
	RoomID string `json:"room_id"`
	Hp     int64  `json:"hp"`
	MaxHp  int64  `json:"max_hp"`
	World  string `json:"world"`
}

func (q *Queries) SavePlayer(ctx context.Context, arg SavePlayerParams) error {
	_, err := q.db.ExecContext(ctx, savePlayer,
		arg.RoomID,
		arg.Hp,
		arg.MaxHp,
		arg.World,
	)
	return err
}

const seedPlayer = `-- name: SeedPlayer :exec
INSERT INTO player (id, name, room_id, hp, max_hp, world) VALUES (1, ?, ?, ?, ?, ?)
`

type SeedPlayerParams struct {
	Name   string `json:"name"`
	RoomID string `json:"room_id"`
	Hp     int64  `json:"hp"`
	MaxHp  int64  `json:"max_hp"`
	World  string `json:"world"`
}

func (q *Queries) SeedPlayer(ctx context.Context, arg SeedPlayerParams) error {
	_, err := q.db.ExecContext(ctx, seedPlayer,
		arg.Name,
		arg.RoomID,
		arg.Hp,
		arg.MaxHp,
		arg.World,
	)
	return err
}

const unequipArmor = `-- name: UnequipArmor :exec
DELETE FROM equipped_armor WHERE id = 1
`

func (q *Queries) UnequipArmor(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unequipArmor)
	return err
}

const upsertNPCAlive = `-- name: UpsertNPCAlive :exec
INSERT OR REPLACE INTO npc_state (room_id, npc_id, hp, alive) VALUES (?, ?, ?, 1)
`

type UpsertNPCAliveParams struct {
	RoomID string `json:"room_id"`
	NpcID  string `json:"npc_id"`
	Hp     int64  `json:"hp"`
}

func (q *Queries) UpsertNPCAlive(ctx context.Context, arg UpsertNPCAliveParams) error {
	_, err := q.db.ExecContext(ctx, upsertNPCAlive, arg.RoomID, arg.NpcID, arg.Hp)
	return err
}

const upsertNPCDead = `-- name: UpsertNPCDead :exec
INSERT OR REPLACE INTO npc_state (room_id, npc_id, hp, alive) VALUES (?, ?, ?, 0)
`

type UpsertNPCDeadParams struct {
	RoomID string `json:"room_id"`
	NpcID  string `json:"npc_id"`
	Hp     int64  `json:"hp"`
}

func (q *Queries) UpsertNPCDead(ctx context.Context, arg UpsertNPCDeadParams) error {
	_, err := q.db.ExecContext(ctx, upsertNPCDead, arg.RoomID, arg.NpcID, arg.Hp)
	return err
}
