// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quests.sql

package sqliteq

import (
	"context"
	"database/sql"
)

const acceptQuest = `-- name: AcceptQuest :exec
INSERT OR IGNORE INTO quests
 (id, title, description, status, obj_type, obj_target, obj_room,
  obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
  reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
  next_quest_id)
 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AcceptQuestParams struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	ObjType        string         `json:"obj_type"`
	ObjTarget      string         `json:"obj_target"`
	ObjRoom        sql.NullString `json:"obj_room"`
	ObjCount       int64          `json:"obj_count"`
	ObjProgress    int64          `json:"obj_progress"`
	RewardCredits  int64          `json:"reward_credits"`
	RewardXpSkill  sql.NullString `json:"reward_xp_skill"`
	RewardXpAmount int64          `json:"reward_xp_amount"`
	RewardItemID   sql.NullString `json:"reward_item_id"`
	RewardItemName sql.NullString `json:"reward_item_name"`
	RewardItemDesc sql.NullString `json:"reward_item_desc"`
	GiverNpcID     sql.NullString `json:"giver_npc_id"`
	AcceptedAt     int64          `json:"accepted_at"`
	NextQuestID    string         `json:"next_quest_id"`
}

func (q *Queries) AcceptQuest(ctx context.Context, arg AcceptQuestParams) error {
	_, err := q.db.ExecContext(ctx, acceptQuest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ObjType,
		arg.ObjTarget,
		arg.ObjRoom,
		arg.ObjCount,
		arg.ObjProgress,
		arg.RewardCredits,
		arg.RewardXpSkill,
		arg.RewardXpAmount,
		arg.RewardItemID,
		arg.RewardItemName,
		arg.RewardItemDesc,
		arg.GiverNpcID,
		arg.AcceptedAt,
		arg.NextQuestID,
	)
	return err
}

const completeQuest = `-- name: CompleteQuest :exec
UPDATE quests SET status = 'completed' WHERE id = ?
`

func (q *Queries) CompleteQuest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, completeQuest, id)
	return err
}

const failQuest = `-- name: FailQuest :exec
UPDATE quests SET status = 'failed' WHERE id = ?
`

func (q *Queries) FailQuest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, failQuest, id)
	return err
}

const getQuest = `-- name: GetQuest :one
SELECT id, title, description, status, obj_type, obj_target, obj_room,
       obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
       reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
       next_quest_id
FROM quests WHERE id = ?
`

func (q *Queries) GetQuest(ctx context.Context, id string) (Quest, error) {
	row := q.db.QueryRowContext(ctx, getQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ObjType,
		&i.ObjTarget,
		&i.ObjRoom,
		&i.ObjCount,
		&i.ObjProgress,
		&i.RewardCredits,
		&i.RewardXpSkill,
		&i.RewardXpAmount,
		&i.RewardItemID,
		&i.RewardItemName,
		&i.RewardItemDesc,
		&i.GiverNpcID,
		&i.AcceptedAt,
		&i.NextQuestID,
	)
	return i, err
}

const listActiveQuestIDs = `-- name: ListActiveQuestIDs :many
SELECT id FROM quests WHERE status = 'active'
`

func (q *Queries) ListActiveQuestIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveQuestIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveQuests = `-- name: ListActiveQuests :many
SELECT id, title, description, status, obj_type, obj_target, obj_room,
       obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
       reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
       next_quest_id
FROM quests WHERE status = 'active'
`

func (q *Queries) ListActiveQuests(ctx context.Context) ([]Quest, error) {
	rows, err := q.db.QueryContext(ctx, listActiveQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ObjType,
			&i.ObjTarget,
			&i.ObjRoom,
			&i.ObjCount,
			&i.ObjProgress,
			&i.RewardCredits,
			&i.RewardXpSkill,
			&i.RewardXpAmount,
			&i.RewardItemID,
			&i.RewardItemName,
			&i.RewardItemDesc,
			&i.GiverNpcID,
			&i.AcceptedAt,
			&i.NextQuestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveQuestsByTypeTarget = `-- name: ListActiveQuestsByTypeTarget :many
SELECT id, title, description, status, obj_type, obj_target, obj_room,
       obj_count, obj_progress, reward_credits, reward_xp_skill, reward_xp_amount,
       reward_item_id, reward_item_name, reward_item_desc, giver_npc_id, accepted_at,
       next_quest_id
FROM quests WHERE status = 'active' AND obj_type = ? AND obj_target = ?
`

type ListActiveQuestsByTypeTargetParams struct {
	ObjType   string `json:"obj_type"`
	ObjTarget string `json:"obj_target"`
}

func (q *Queries) ListActiveQuestsByTypeTarget(ctx context.Context, arg ListActiveQuestsByTypeTargetParams) ([]Quest, error) {
	rows, err := q.db.QueryContext(ctx, listActiveQuestsByTypeTarget, arg.ObjType, arg.ObjTarget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ObjType,
			&i.ObjTarget,
			&i.ObjRoom,
			&i.ObjCount,
			&i.ObjProgress,
			&i.RewardCredits,
			&i.RewardXpSkill,
			&i.RewardXpAmount,
			&i.RewardItemID,
			&i.RewardItemName,
			&i.RewardItemDesc,
			&i.GiverNpcID,
			&i.AcceptedAt,
			&i.NextQuestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const progressQuest = `-- name: ProgressQuest :exec
UPDATE quests SET obj_progress = obj_progress + ? WHERE id = ? AND status = 'active'
`

type ProgressQuestParams struct {
	ObjProgress int64  `json:"obj_progress"`
	ID          string `json:"id"`
}

func (q *Queries) ProgressQuest(ctx context.Context, arg ProgressQuestParams) error {
	_, err := q.db.ExecContext(ctx, progressQuest, arg.ObjProgress, arg.ID)
	return err
}
