// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqliteq

import (
	"context"
)

const listAllSkills = `-- name: ListAllSkills :many
SELECT skill, level, xp FROM player_skills
`

func (q *Queries) ListAllSkills(ctx context.Context) ([]PlayerSkill, error) {
	rows, err := q.db.QueryContext(ctx, listAllSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerSkill{}
	for rows.Next() {
		var i PlayerSkill
		if err := rows.Scan(&i.Skill, &i.Level, &i.Xp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSkill = `-- name: LoadSkill :one
SELECT level, xp FROM player_skills WHERE skill = ?
`

type LoadSkillRow struct {
	Level int64 `json:"level"`
	Xp    int64 `json:"xp"`
}

func (q *Queries) LoadSkill(ctx context.Context, skill string) (LoadSkillRow, error) {
	row := q.db.QueryRowContext(ctx, loadSkill, skill)
	var i LoadSkillRow
	err := row.Scan(&i.Level, &i.Xp)
	return i, err
}

const upsertSkill = `-- name: UpsertSkill :exec
INSERT INTO player_skills (skill, level, xp) VALUES (?, ?, ?)
ON CONFLICT(skill) DO UPDATE SET level = excluded.level, xp = excluded.xp
`

type UpsertSkillParams struct {
	Skill string `json:"skill"`
	Level int64  `json:"level"`
	Xp    int64  `json:"xp"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkill, arg.Skill, arg.Level, arg.Xp)
	return err
}
