// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weather.sql

package sqliteq

import (
	"context"
)

const getWeatherCondition = `-- name: GetWeatherCondition :one
SELECT condition FROM weather_state WHERE biome = ?
`

func (q *Queries) GetWeatherCondition(ctx context.Context, biome string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWeatherCondition, biome)
	var condition string
	err := row.Scan(&condition)
	return condition, err
}

const getWeatherState = `-- name: GetWeatherState :one
SELECT condition, expires_action FROM weather_state WHERE biome = ?
`

type GetWeatherStateRow struct {
	Condition     string `json:"condition"`
	ExpiresAction int64  `json:"expires_action"`
}

func (q *Queries) GetWeatherState(ctx context.Context, biome string) (GetWeatherStateRow, error) {
	row := q.db.QueryRowContext(ctx, getWeatherState, biome)
	var i GetWeatherStateRow
	err := row.Scan(&i.Condition, &i.ExpiresAction)
	return i, err
}

const upsertWeatherState = `-- name: UpsertWeatherState :exec
INSERT INTO weather_state (biome, condition, expires_action) VALUES (?, ?, ?)
ON CONFLICT(biome) DO UPDATE SET condition = excluded.condition, expires_action = excluded.expires_action
`

type UpsertWeatherStateParams struct {
	Biome         string `json:"biome"`
	Condition     string `json:"condition"`
	ExpiresAction int64  `json:"expires_action"`
}

func (q *Queries) UpsertWeatherState(ctx context.Context, arg UpsertWeatherStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeatherState, arg.Biome, arg.Condition, arg.ExpiresAction)
	return err
}
