// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: world_seed.sql

package sqliteq

import (
	"context"
)

const countStartingItem = `-- name: CountStartingItem :one
SELECT COUNT(*) FROM inventory WHERE item_id = 'wooden-pickaxe'
`

func (q *Queries) CountStartingItem(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStartingItem)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertStartingItem = `-- name: InsertStartingItem :exec
INSERT OR IGNORE INTO inventory (item_id, item_name, item_desc) VALUES (?, ?, ?)
`

type InsertStartingItemParams struct {
	ItemID   string `json:"item_id"`
	ItemName string `json:"item_name"`
	ItemDesc string `json:"item_desc"`
}

func (q *Queries) InsertStartingItem(ctx context.Context, arg InsertStartingItemParams) error {
	_, err := q.db.ExecContext(ctx, insertStartingItem, arg.ItemID, arg.ItemName, arg.ItemDesc)
	return err
}

const seedCrystalShard = `-- name: SeedCrystalShard :exec
INSERT OR IGNORE INTO crystal_shards (shard_id, biome, collected, collected_at) VALUES (?, ?, 0, 0)
`

type SeedCrystalShardParams struct {
	ShardID string `json:"shard_id"`
	Biome   string `json:"biome"`
}

func (q *Queries) SeedCrystalShard(ctx context.Context, arg SeedCrystalShardParams) error {
	_, err := q.db.ExecContext(ctx, seedCrystalShard, arg.ShardID, arg.Biome)
	return err
}
